# Generated by Django 4.0.2 on 2022-03-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_auto_20220316_1445'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privacypolicyconsent',
            name='unique_privacy_policy_consent',
        ),
    ]
