# Generated by Django 4.0.2 on 2022-03-30 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privacy', '0002_auto_20220316_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(help_text='True if the request was not yet executed')),
                ('execute_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='deleteaccountrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)), fields=('user',), name='unique_delete_account_request'
            ),
        ),
    ]
