# Generated by Django 4.0.2 on 2022-04-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0003_deleteaccountrequest_and_more'),
        ('privacy', '0003_remove_privacypolicyconsent_unique_privacy_policy_consent'),
    ]

    operations = []
