# Generated by Django 4.0.2 on 2022-03-03 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConceptEMPElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sub_area', models.CharField(max_length=255)),
                (
                    'sub_area_sensors',
                    models.TextField(
                        help_text='All sensors that can measure within the sub area that the EMP element address'
                    ),
                ),
                (
                    'sub_area_external_id',
                    models.CharField(help_text='ID used to identify sub area in external systems', max_length=50),
                ),
                (
                    'consumers',
                    models.TextField(
                        help_text='Overview of what consumers are affected and should be measured directly or indirectly'
                    ),
                ),
                ('consumer_sensors', models.TextField(help_text='Sensors that are available on the equipment ')),
                (
                    'baseline_average_power',
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baseline average MW'
                    ),
                ),
                (
                    'target_average_power',
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)], verbose_name='Target average MW'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Concept EMP element',
            },
        ),
    ]
