# Generated by Django 4.0.2 on 2022-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0002_emp_rename_sub_area_conceptempelement_subarea_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customempelement',
            constraint=models.UniqueConstraint(fields=('emp', 'concept_emp_element'), name='unique_custom_emp_element'),
        ),
    ]
