# Generated by Django 4.0.2 on 2022-05-10 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0003_customempelement_unique_custom_emp_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customempelement',
            name='baseline_average',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customempelement',
            name='target_average',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_rig_baseline_average',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emp',
            name='total_rig_target_average',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
