# Generated by Django 4.0.2 on 2022-07-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0004_alter_customempelement_baseline_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmpInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomEmpInitiativePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'phase',
                    models.CharField(
                        choices=[
                            ('TRANSIT', 'Transit / Stand by'),
                            ('POSITIONING', 'Positioning'),
                            ('TOP_HOLE_SECTION', 'Top hole section'),
                            ('TRANSPORT_SECTION', 'Transport section'),
                            ('RESERVOIR_SECTION', 'Reservoir section'),
                            ('COMPLETION', 'Completion'),
                            ('WELL_INTERVENTION', 'Well intervention'),
                            ('PLUG_AND_ABANDON', 'Plug and abandon'),
                            ('WAITING_ON_WEATHER', 'Waiting on weather'),
                            ('DOWNTIME', 'Downtime'),
                            ('MOBILIZING', 'Mobilizing'),
                            ('WARM_STACKED', 'Warm stacked'),
                            ('COLD_STACKED', 'Cold stacked'),
                        ],
                        max_length=32,
                    ),
                ),
                ('default', models.FloatField()),
                ('dp', models.FloatField()),
                ('pos_moore', models.FloatField()),
                ('anchor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomEnergyUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomEnergyUsePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'phase',
                    models.CharField(
                        choices=[
                            ('TRANSIT', 'Transit / Stand by'),
                            ('POSITIONING', 'Positioning'),
                            ('TOP_HOLE_SECTION', 'Top hole section'),
                            ('TRANSPORT_SECTION', 'Transport section'),
                            ('RESERVOIR_SECTION', 'Reservoir section'),
                            ('COMPLETION', 'Completion'),
                            ('WELL_INTERVENTION', 'Well intervention'),
                            ('PLUG_AND_ABANDON', 'Plug and abandon'),
                            ('WAITING_ON_WEATHER', 'Waiting on weather'),
                            ('DOWNTIME', 'Downtime'),
                            ('MOBILIZING', 'Mobilizing'),
                            ('WARM_STACKED', 'Warm stacked'),
                            ('COLD_STACKED', 'Cold stacked'),
                        ],
                        max_length=32,
                    ),
                ),
                ('default', models.FloatField()),
                ('dp', models.FloatField()),
                ('pos_moore', models.FloatField()),
                ('anchor', models.FloatField()),
                ('season', models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOperationEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Custom Operation Efficiency',
                'verbose_name_plural': 'Custom Operation Efficiencies',
            },
        ),
        migrations.CreateModel(
            name='CustomOperationEfficiencyPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'phase',
                    models.CharField(
                        choices=[
                            ('TRANSIT', 'Transit / Stand by'),
                            ('POSITIONING', 'Positioning'),
                            ('TOP_HOLE_SECTION', 'Top hole section'),
                            ('TRANSPORT_SECTION', 'Transport section'),
                            ('RESERVOIR_SECTION', 'Reservoir section'),
                            ('COMPLETION', 'Completion'),
                            ('WELL_INTERVENTION', 'Well intervention'),
                            ('PLUG_AND_ABANDON', 'Plug and abandon'),
                            ('WAITING_ON_WEATHER', 'Waiting on weather'),
                            ('DOWNTIME', 'Downtime'),
                            ('MOBILIZING', 'Mobilizing'),
                            ('WARM_STACKED', 'Warm stacked'),
                            ('COLD_STACKED', 'Cold stacked'),
                        ],
                        max_length=32,
                    ),
                ),
                ('default', models.FloatField()),
                ('dp', models.FloatField()),
                ('pos_moore', models.FloatField()),
                ('anchor', models.FloatField()),
                (
                    'operation_efficiency',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emps.customoperationefficiency'),
                ),
            ],
        ),
    ]
