# Generated by Django 4.0.2 on 2022-07-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0005_customempinitiative_customempinitiativephase_and_more'),
        ('projects', '0027_conceptcarboncapturestoragesystem_conceptcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customoperationefficiency',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rigplanner'),
        ),
        migrations.AddField(
            model_name='customenergyusephase',
            name='energy_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emps.customenergyuse'),
        ),
        migrations.AddField(
            model_name='customenergyuse',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rigplanner'),
        ),
        migrations.AddField(
            model_name='customempinitiativephase',
            name='emp_initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emps.customempinitiative'),
        ),
        migrations.AddField(
            model_name='customempinitiative',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rigplanner'),
        ),
        migrations.AlterUniqueTogether(
            name='customoperationefficiencyphase',
            unique_together={('operation_efficiency', 'phase')},
        ),
        migrations.AlterUniqueTogether(
            name='customenergyusephase',
            unique_together={('energy_use', 'phase', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='customempinitiativephase',
            unique_together={('emp_initiative', 'phase')},
        ),
    ]
