# Generated by Django 4.0.2 on 2022-08-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_rigplanner_single_rig_planner_rig_and_more'),
        ('emps', '0006_customoperationefficiency_rig_planner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customenergyuse',
            name='rig_planner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.rigplanner'),
        ),
    ]
