# Generated by Django 4.0.2 on 2022-08-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0007_alter_customenergyuse_rig_planner'),
        ('emps', '0007_customempinitiative_group'),
    ]

    operations = []
