# Generated by Django 4.0.2 on 2022-09-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_wellplannerphase_wellplannermode_and_more'),
        ('emps', '0008_merge_20220826_1305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customempinitiativephase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customenergyusephase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customempinitiativephase',
            name='mode_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AddField(
            model_name='customempinitiativephase',
            name='phase_model',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'
            ),
        ),
        migrations.AddField(
            model_name='customempinitiativephase',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customenergyusephase',
            name='mode_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AddField(
            model_name='customenergyusephase',
            name='phase_model',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'
            ),
        ),
        migrations.AddField(
            model_name='customenergyusephase',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customempinitiativephase',
            unique_together={('emp_initiative', 'phase_model', 'mode_model')},
        ),
        migrations.AlterUniqueTogether(
            name='customenergyusephase',
            unique_together={('energy_use', 'season', 'phase_model', 'mode_model')},
        ),
    ]
