# Generated by Django 4.0.2 on 2022-09-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_remove_wellplannercompletestep_operation_efficiencies_and_more'),
        ('emps', '0008_merge_20220826_1305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customoperationefficiencyphase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customoperationefficiencyphase',
            name='operation_efficiency',
        ),
        migrations.DeleteModel(
            name='CustomOperationEfficiency',
        ),
        migrations.DeleteModel(
            name='CustomOperationEfficiencyPhase',
        ),
    ]
