# Generated by Django 4.0.2 on 2022-09-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0026_alter_wellplannercompletestep_mode_model_and_more'),
        ('emps', '0009_alter_customempinitiativephase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customempinitiativephase',
            name='mode_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='customempinitiativephase',
            name='phase_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'),
        ),
        migrations.AlterField(
            model_name='customenergyusephase',
            name='mode_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='customenergyusephase',
            name='phase_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'),
        ),
    ]
