# Generated by Django 4.0.2 on 2022-09-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0028_rename_mode_model_wellplannercompletestep_mode_and_more'),
        ('emps', '0011_remove_customempinitiativephase_phase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customempinitiativephase',
            old_name='mode_model',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='customempinitiativephase',
            old_name='phase_model',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='customenergyusephase',
            old_name='mode_model',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='customenergyusephase',
            old_name='phase_model',
            new_name='phase',
        ),
        migrations.AlterUniqueTogether(
            name='customempinitiativephase',
            unique_together={('emp_initiative', 'phase', 'mode')},
        ),
        migrations.AlterUniqueTogether(
            name='customenergyusephase',
            unique_together={('energy_use', 'season', 'phase', 'mode')},
        ),
    ]
