# Generated by Django 4.0.2 on 2022-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0012_rename_mode_model_customempinitiativephase_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customempinitiativephase',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='customempinitiativephase',
            name='default',
        ),
        migrations.RemoveField(
            model_name='customempinitiativephase',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='customempinitiativephase',
            name='pos_moore',
        ),
        migrations.RemoveField(
            model_name='customenergyusephase',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='customenergyusephase',
            name='default',
        ),
        migrations.RemoveField(
            model_name='customenergyusephase',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='customenergyusephase',
            name='pos_moore',
        ),
    ]
