# Generated by Django 4.0.2 on 2022-09-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0028_rename_mode_model_wellplannercompletestep_mode_and_more'),
        ('emps', '0013_remove_customempinitiativephase_anchor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customempinitiativephase',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='customempinitiativephase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannerphase'),
        ),
        migrations.AlterField(
            model_name='customenergyusephase',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='customenergyusephase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannerphase'),
        ),
    ]
