# Generated by Django 4.0.2 on 2022-09-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0009_alter_customoperationefficiencyphase_unique_together_and_more'),
        ('emps', '0014_alter_customempinitiativephase_mode_and_more'),
    ]

    operations = []
