# Generated by Django 4.0.2 on 2022-09-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0015_merge_20220914_0613'),
        ('projects', '0032_auto_20220922_0905'),
        ('emissions', '0001_initial'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='customempinitiative',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='customenergyuse',
            name='rig_planner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
