# Generated by Django 4.0.2 on 2022-09-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0017_rename_rig_planner_customempinitiative_asset_and_more'),
        ('emissions', '0006_customempinitiative_customenergyuse_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.AlterModelTable(
                    name='CustomEmpInitiative',
                    table='emissions_customempinitiative',
                ),
                migrations.AlterModelTable(
                    name='CustomEnergyUse',
                    table='emissions_customenergyuse',
                ),
                migrations.AlterModelTable(
                    name='CustomEnergyUsePhase',
                    table='emissions_customenergyusephase',
                ),
                migrations.AlterModelTable(
                    name='CustomEmpInitiativePhase',
                    table='emissions_customempinitiativephase',
                ),
            ],
        ),
    ]
