import datetime

from apps.rigs.models import Airgap, DPClass, HighMediumLow, RigStatus, TopsideDesign

CUSTOM_JACKUP_RIG_DRAFT_DATA = {
    "name": "",
    "manager": "",
    "design": "",
    "build_yard": "",
    "rig_status": "",
    "delivery_date": None,
    "special_survey_due": None,
    "end_of_last_contract": None,
    "months_in_operation_last_year": None,
    "months_in_operation_last_3_years": None,
    "design_score": "",
    "topside_design": "",
    "quarters_capacity": None,
    "rig_water_depth": None,
    "variable_load": None,
    "hull_breadth": None,
    "hull_depth": None,
    "hull_length": None,
    "derrick_height": None,
    "derrick_capacity": None,
    "drawworks_power": None,
    "total_cranes": None,
    "crane_capacity": None,
    "total_bop_rams": None,
    "bop_diameter_wp_max": None,
    "bop_wp_max": None,
    "number_of_bop_stacks": None,
    "mudpump_quantity": None,
    "liquid_mud": None,
    "mud_total_power": None,
    "shaleshaker_total": None,
    "engine_power": None,
    "engine_quantity": None,
    "engine_total": None,
    "generator_power": None,
    "generator_quantity": None,
    "generator_total": None,
    "offline_stand_building": None,
    "auto_pipe_handling": None,
    "dual_activity": None,
    "drilltronic": None,
    "dynamic_drilling_guide": None,
    "process_automation_platform": None,
    "automatic_tripping": None,
    "closed_bus": None,
    "scr": None,
    "hybrid": None,
    "hvac_heat_recovery": None,
    "freshwater_cooling_systems": None,
    "seawater_cooling_systems": None,
    "operator_awareness_dashboard": None,
    "hpu_optimization": None,
    "optimized_heat_tracing_system": None,
    "floodlighting_optimization": None,
    "vfds_on_aux_machinery": None,
    "cantilever_reach": None,
    "cantilever_lateral": None,
    "cantilever_capacity": None,
    "leg_length": None,
    "leg_spacing": None,
    "subsea_drilling": None,
    "enhanced_legs": None,
    "day_rate": None,
    "spread_cost": None,
    "tugs_no_used": None,
    "jack_up_time": None,
    "jack_down_time": None,
    "draft": True,
}


CUSTOM_JACKUP_RIG_PUBLIC_DATA = {
    "name": "Custom Jackup 1",
    "manager": "Custom Jackup Manager 1",
    "design": "Custom Jackup Design 1",
    "build_yard": "Custom Jackup Yard 1",
    "rig_status": RigStatus.DRILLING,
    "delivery_date": datetime.date.today().isoformat(),
    "special_survey_due": datetime.date.today().isoformat(),
    "end_of_last_contract": datetime.date.today().isoformat(),
    "months_in_operation_last_year": 0,
    "months_in_operation_last_3_years": 0,
    "design_score": HighMediumLow.LOW,
    "topside_design": TopsideDesign.NOV,
    "quarters_capacity": 10.0,
    "rig_water_depth": 0.0,
    "variable_load": 0.0,
    "hull_breadth": 100.0,
    "hull_depth": 10.0,
    "hull_length": 100.0,
    "derrick_height": 50.0,
    "derrick_capacity": 500000.0,
    "drawworks_power": 1000.0,
    "total_cranes": 1.0,
    "crane_capacity": 10.0,
    "total_bop_rams": 1.0,
    "bop_diameter_wp_max": 10.0,
    "bop_wp_max": 5000.0,
    "number_of_bop_stacks": 1.0,
    "mudpump_quantity": 1,
    "liquid_mud": 1000.0,
    "mud_total_power": 1000.0,
    "shaleshaker_total": 0.0,
    "engine_power": 0.0,
    "engine_quantity": 0,
    "engine_total": 0.0,
    "generator_power": 0.0,
    "generator_quantity": 0,
    "generator_total": 0.0,
    "offline_stand_building": False,
    "auto_pipe_handling": False,
    "dual_activity": False,
    "drilltronic": False,
    "dynamic_drilling_guide": False,
    "process_automation_platform": False,
    "automatic_tripping": False,
    "closed_bus": False,
    "scr": False,
    "hybrid": False,
    "hvac_heat_recovery": False,
    "freshwater_cooling_systems": False,
    "seawater_cooling_systems": False,
    "operator_awareness_dashboard": False,
    "hpu_optimization": False,
    "optimized_heat_tracing_system": False,
    "floodlighting_optimization": False,
    "vfds_on_aux_machinery": False,
    "cantilever_reach": 0.0,
    "cantilever_lateral": 0.0,
    "cantilever_capacity": 1000000.0,
    "leg_length": 100.0,
    "leg_spacing": 100.0,
    "subsea_drilling": False,
    "enhanced_legs": False,
    "day_rate": 300000,
    "spread_cost": 100000,
    "tugs_no_used": 2,
    "jack_up_time": 1.4,
    "jack_down_time": 1.4,
    "draft": False,
}


CUSTOM_SEMI_RIG_DRAFT_DATA = {
    "name": "",
    "manager": "",
    "design": "",
    "build_yard": "",
    "rig_status": "",
    "delivery_date": None,
    "special_survey_due": None,
    "end_of_last_contract": None,
    "months_in_operation_last_year": None,
    "months_in_operation_last_3_years": None,
    "design_score": "",
    "topside_design": "",
    "quarters_capacity": None,
    "rig_water_depth": None,
    "variable_load": None,
    "hull_breadth": None,
    "hull_depth": None,
    "hull_length": None,
    "derrick_height": None,
    "derrick_capacity": None,
    "drawworks_power": None,
    "total_cranes": None,
    "crane_capacity": None,
    "total_bop_rams": None,
    "bop_diameter_wp_max": None,
    "bop_wp_max": None,
    "number_of_bop_stacks": None,
    "mudpump_quantity": None,
    "liquid_mud": None,
    "mud_total_power": None,
    "shaleshaker_total": None,
    "engine_power": None,
    "engine_quantity": None,
    "engine_total": None,
    "generator_power": None,
    "generator_quantity": None,
    "generator_total": None,
    "offline_stand_building": None,
    "auto_pipe_handling": None,
    "dual_activity": None,
    "drilltronic": None,
    "dynamic_drilling_guide": None,
    "process_automation_platform": None,
    "automatic_tripping": None,
    "closed_bus": None,
    "scr": None,
    "hybrid": None,
    "hvac_heat_recovery": None,
    "freshwater_cooling_systems": None,
    "seawater_cooling_systems": None,
    "operator_awareness_dashboard": None,
    "hpu_optimization": None,
    "optimized_heat_tracing_system": None,
    "floodlighting_optimization": None,
    "vfds_on_aux_machinery": None,
    "equipment_load": "",
    "drillfloor_efficiency": "",
    "hull_concept_score": None,
    "hull_design_eco_score": None,
    "dp": None,
    "dp_class": "",
    "thruster_assist": None,
    "total_anchors": None,
    "anchor_standalone": None,
    "airgap": "",
    "draft_depth": None,
    "displacement": None,
    "dual_derrick": None,
    "active_heave_drawwork": None,
    "cmc_with_active_heave": None,
    "ram_system": None,
    "tripsaver": None,
    "day_rate": None,
    "spread_cost": None,
    "tugs_no_used": None,
    "move_speed": None,
    "draft": True,
}


CUSTOM_SEMI_RIG_PUBLIC_DATA = {
    "name": "Custom Semi 1",
    "manager": "Some Semi Manager 1",
    "design": "Some Semi Design 1",
    "build_yard": "Some Semi Yard 1",
    "rig_status": RigStatus.DRILLING,
    "delivery_date": datetime.date.today().isoformat(),
    "special_survey_due": datetime.date.today().isoformat(),
    "end_of_last_contract": datetime.date.today().isoformat(),
    "months_in_operation_last_year": 4,
    "months_in_operation_last_3_years": 12,
    "design_score": HighMediumLow.LOW,
    "topside_design": TopsideDesign.NOV,
    "quarters_capacity": 123.0,
    "rig_water_depth": 140.0,
    "variable_load": 213.0,
    "hull_breadth": 400.0,
    "hull_depth": 100.0,
    "hull_length": 500.0,
    "derrick_height": 200.0,
    "derrick_capacity": 500000.0,
    "drawworks_power": 1000.0,
    "total_cranes": 10.0,
    "crane_capacity": 300.0,
    "total_bop_rams": 10.0,
    "bop_diameter_wp_max": 30.0,
    "bop_wp_max": 5001.0,
    "number_of_bop_stacks": 2.0,
    "mudpump_quantity": 10,
    "liquid_mud": 1000.0,
    "mud_total_power": 20000.0,
    "shaleshaker_total": 10.0,
    "engine_power": 20000.0,
    "engine_quantity": 10,
    "engine_total": 100000.0,
    "generator_power": 20000.0,
    "generator_quantity": 10,
    "generator_total": 100000.0,
    "offline_stand_building": True,
    "auto_pipe_handling": True,
    "dual_activity": True,
    "drilltronic": True,
    "dynamic_drilling_guide": True,
    "process_automation_platform": True,
    "automatic_tripping": True,
    "closed_bus": True,
    "scr": True,
    "hybrid": True,
    "hvac_heat_recovery": True,
    "freshwater_cooling_systems": True,
    "seawater_cooling_systems": True,
    "operator_awareness_dashboard": True,
    "hpu_optimization": True,
    "optimized_heat_tracing_system": True,
    "floodlighting_optimization": True,
    "vfds_on_aux_machinery": True,
    "equipment_load": HighMediumLow.LOW,
    "drillfloor_efficiency": HighMediumLow.LOW,
    "hull_concept_score": 8.0,
    "hull_design_eco_score": 8.0,
    "dp": True,
    "dp_class": DPClass.DP2,
    "thruster_assist": True,
    "total_anchors": 15.0,
    "anchor_standalone": False,
    "airgap": Airgap.S,
    "draft_depth": 144.0,
    "displacement": 5001.0,
    "dual_derrick": False,
    "active_heave_drawwork": False,
    "cmc_with_active_heave": False,
    "ram_system": False,
    "tripsaver": True,
    "day_rate": 300000,
    "spread_cost": 100000,
    "tugs_no_used": 2,
    "move_speed": 6,
    "draft": False,
}

CUSTOM_DRILLSHIP_DRAFT_DATA = {
    "name": "",
    "manager": "",
    "design": "",
    "build_yard": "",
    "rig_status": "",
    "delivery_date": None,
    "special_survey_due": None,
    "end_of_last_contract": None,
    "months_in_operation_last_year": None,
    "months_in_operation_last_3_years": None,
    "design_score": "",
    "topside_design": "",
    "quarters_capacity": None,
    "hull_breadth": None,
    "hull_depth": None,
    "hull_length": None,
    "derrick_height": None,
    "derrick_capacity": None,
    "drawworks_power": None,
    "total_cranes": None,
    "crane_capacity": None,
    "total_bop_rams": None,
    "bop_diameter_wp_max": None,
    "bop_wp_max": None,
    "number_of_bop_stacks": None,
    "mudpump_quantity": None,
    "liquid_mud": None,
    "mud_total_power": None,
    "shaleshaker_total": None,
    "engine_power": None,
    "engine_quantity": None,
    "engine_total": None,
    "generator_power": None,
    "generator_quantity": None,
    "generator_total": None,
    "offline_stand_building": None,
    "auto_pipe_handling": None,
    "dual_activity": None,
    "drilltronic": None,
    "dynamic_drilling_guide": None,
    "process_automation_platform": None,
    "automatic_tripping": None,
    "closed_bus": None,
    "scr": None,
    "hybrid": None,
    "hvac_heat_recovery": None,
    "freshwater_cooling_systems": None,
    "seawater_cooling_systems": None,
    "operator_awareness_dashboard": None,
    "hpu_optimization": None,
    "optimized_heat_tracing_system": None,
    "floodlighting_optimization": None,
    "vfds_on_aux_machinery": None,
    "equipment_load": "",
    "drillfloor_efficiency": "",
    "rig_water_depth": None,
    "variable_load": None,
    "hull_concept_score": None,
    "hull_design_eco_score": None,
    "dp": None,
    "dp_class": "",
    "draft_depth": None,
    "displacement": None,
    "riser_on_board_outfitted": None,
    "riser_storage_inside_hull": None,
    "split_funnels_free_stern_deck": None,
    "dual_derrick": None,
    "active_heave_drawwork": None,
    "cmc_with_active_heave": None,
    "ram_system": None,
    "tripsaver": None,
    "day_rate": None,
    "spread_cost": None,
    "tugs_no_used": None,
    "draft": True,
}


CUSTOM_DRILLSHIP_PUBLIC_DATA = {
    "name": "Custom Drillship 1",
    "manager": "Manager",
    "design": "Design",
    "build_yard": "Build yard",
    "rig_status": RigStatus.DRILLING,
    "delivery_date": datetime.date.today().isoformat(),
    "special_survey_due": datetime.date.today().isoformat(),
    "end_of_last_contract": datetime.date.today().isoformat(),
    "months_in_operation_last_year": 1,
    "months_in_operation_last_3_years": 1,
    "design_score": HighMediumLow.LOW,
    "topside_design": TopsideDesign.NOV,
    "quarters_capacity": 10.0,
    "hull_breadth": 100.0,
    "hull_depth": 10.0,
    "hull_length": 100.0,
    "derrick_height": 50.0,
    "derrick_capacity": 500000.0,
    "drawworks_power": 1000.0,
    "total_cranes": 1.0,
    "crane_capacity": 10.0,
    "total_bop_rams": 1.0,
    "bop_diameter_wp_max": 10.0,
    "bop_wp_max": 5000.0,
    "number_of_bop_stacks": 1.0,
    "mudpump_quantity": 1,
    "liquid_mud": 1000.0,
    "mud_total_power": 1000.0,
    "shaleshaker_total": 1.0,
    "engine_power": 1.0,
    "engine_quantity": 1,
    "engine_total": 1.0,
    "generator_power": 1.0,
    "generator_quantity": 1,
    "generator_total": 1.0,
    "offline_stand_building": False,
    "auto_pipe_handling": False,
    "dual_activity": False,
    "drilltronic": False,
    "dynamic_drilling_guide": False,
    "process_automation_platform": False,
    "automatic_tripping": False,
    "closed_bus": False,
    "scr": False,
    "hybrid": False,
    "hvac_heat_recovery": False,
    "freshwater_cooling_systems": False,
    "seawater_cooling_systems": False,
    "operator_awareness_dashboard": False,
    "hpu_optimization": False,
    "optimized_heat_tracing_system": False,
    "floodlighting_optimization": False,
    "vfds_on_aux_machinery": False,
    "equipment_load": HighMediumLow.LOW,
    "drillfloor_efficiency": HighMediumLow.LOW,
    "rig_water_depth": 1.0,
    "variable_load": 1.0,
    "hull_concept_score": 1.0,
    "hull_design_eco_score": 1.0,
    "dp": False,
    "dp_class": "DP3",
    "draft_depth": 50.0,
    "displacement": 5000.0,
    "riser_on_board_outfitted": 1.0,
    "riser_storage_inside_hull": False,
    "split_funnels_free_stern_deck": False,
    "dual_derrick": False,
    "active_heave_drawwork": False,
    "cmc_with_active_heave": False,
    "ram_system": False,
    "tripsaver": False,
    "day_rate": 300000,
    "spread_cost": 100000,
    "tugs_no_used": 2,
    "draft": False,
}


CUSTOM_SEMI_RIG_SERIALIZED_PUBLIC_DATA = {
    **CUSTOM_SEMI_RIG_PUBLIC_DATA,
    "delivery_date": datetime.date.today(),
    "special_survey_due": datetime.date.today(),
    "end_of_last_contract": datetime.date.today(),
}
CUSTOM_SEMI_RIG_SERIALIZED_DRAFT_DATA = {
    **CUSTOM_SEMI_RIG_DRAFT_DATA,
    "delivery_date": None,
    "special_survey_due": None,
    "end_of_last_contract": None,
}
CUSTOM_JACKUP_RIG_SERIALIZED_PUBLIC_DATA = {
    **CUSTOM_JACKUP_RIG_PUBLIC_DATA,
    "delivery_date": datetime.date.today(),
    "special_survey_due": datetime.date.today(),
    "end_of_last_contract": datetime.date.today(),
}
CUSTOM_JACKUP_RIG_SERIALIZED_DRAFT_DATA = {
    **CUSTOM_JACKUP_RIG_DRAFT_DATA,
    "delivery_date": None,
    "special_survey_due": None,
    "end_of_last_contract": None,
}
CUSTOM_DRILLSHIP_SERIALIZED_PUBLIC_DATA = {
    **CUSTOM_DRILLSHIP_PUBLIC_DATA,
    "delivery_date": datetime.date.today(),
    "special_survey_due": datetime.date.today(),
    "end_of_last_contract": datetime.date.today(),
}
CUSTOM_DRILLSHIP_SERIALIZED_DRAFT_DATA = {
    **CUSTOM_DRILLSHIP_DRAFT_DATA,
    "delivery_date": None,
    "special_survey_due": None,
    "end_of_last_contract": None,
}
