# Generated by Django 4.0.2 on 2022-03-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenantinvitation_unique_tenant_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tugs_no_used', models.PositiveIntegerField(help_text='Number of tugs to be used')),
                ('tugs_day_rate', models.FloatField(help_text='Tugs day rate (USD)')),
                ('ahv_no_used', models.PositiveIntegerField(help_text='Number of AHVs to be used')),
                ('ahv_no_days_per_location', models.PositiveIntegerField(help_text='Number of AHV days per location')),
                ('ahv_avg_fuel_consumption', models.FloatField(help_text='Average AHV fuel consumption (t/d)')),
                ('ahv_day_rate', models.FloatField(help_text='AHV day rate (USD)')),
                ('psv_calls_per_week', models.PositiveIntegerField(help_text='PSV calls per week')),
                ('psv_types', models.TextField(help_text="Type of PSV's / names")),
                ('psv_avg_fuel_consumption', models.FloatField(help_text='Average PSV fuel consumption (t/d)')),
                ('psv_day_rate', models.FloatField(help_text='PSV day rate (USD)')),
                (
                    'helicopter_no_flights_per_week',
                    models.PositiveIntegerField(help_text='Helicopter number of flights per week'),
                ),
                ('helicopter_types', models.TextField(help_text='Type of helicopters')),
                (
                    'helicopter_avg_fuel_consumption',
                    models.FloatField(help_text='Helicopter average fuel consumption (t/h)'),
                ),
                ('helicopter_rate_per_trip', models.FloatField(help_text='Helicopter rate per trip (USD)')),
                ('helicopter_fuel_price', models.FloatField(help_text='Helicopter fuel price (USD/t)')),
                ('marine_diesel_oil_price', models.FloatField(help_text='Marine Diesel oil price')),
                ('co2_tax', models.FloatField(help_text='CO2 tax (USD/t)')),
                ('nox_tax', models.FloatField(help_text='NOX tag (USD/t)')),
                ('fuel_total_price', models.FloatField(help_text='Total fuel price')),
                ('fuel_density', models.FloatField(help_text='Fuel density (t/m3)')),
                ('co2_emission_per_tonne_fuel', models.FloatField(help_text='CO2 emission per tonne fuel')),
                ('co2_emission_per_m3_fuel', models.FloatField(help_text='CO2 emission per m3 fuel')),
                (
                    'creator',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
