# Generated by Django 4.0.2 on 2022-03-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0005_alter_conceptjackuprig_end_of_last_contract_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jackup_rigs',
            field=models.ManyToManyField(blank=True, to='rigs.CustomJackupRig'),
        ),
        migrations.AddField(
            model_name='project',
            name='semi_rigs',
            field=models.ManyToManyField(blank=True, to='rigs.CustomSemiRig'),
        ),
    ]
