# Generated by Django 4.0.2 on 2022-04-29 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_alter_conceptwell_casing_data_and_more'),
        ('projects', '0003_project_wells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('block_name', models.CharField(max_length=255)),
                ('operation_start_date', models.DateField()),
                ('operation_end_date', models.DateField()),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='projects.project'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanWellRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'distance_from_previous_location',
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    'distance_to_helicopter_base',
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ('distance_to_psv_base', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_to_ahv_base', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='plan_wells', to='projects.plan'
                    ),
                ),
                (
                    'well',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='wells.customwell'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='wells',
            field=models.ManyToManyField(through='projects.PlanWellRelation', to='wells.CustomWell'),
        ),
        migrations.AddConstraint(
            model_name='planwellrelation',
            constraint=models.UniqueConstraint(fields=('plan', 'well'), name='unique_plan_well_relation'),
        ),
    ]
