# Generated by Django 4.0.2 on 2022-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_plan_planwellrelation_plan_wells_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planwellrelation',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
