# Generated by Django 4.0.2 on 2022-05-04 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_plan_planwellrelation_plan_wells_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ahv_avg_fuel_consumption',
            field=models.FloatField(
                help_text='Average AHV fuel consumption (t/d)',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='ahv_day_rate',
            field=models.FloatField(
                help_text='AHV day rate (USD)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='ahv_no_days_per_location',
            field=models.FloatField(
                help_text='Number of AHV days per location', validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='ahv_no_used',
            field=models.PositiveIntegerField(
                help_text='Number of AHVs to be used',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='co2_emission_per_m3_fuel',
            field=models.FloatField(
                help_text='CO2 emission per m3 fuel',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='co2_emission_per_tonne_fuel',
            field=models.FloatField(
                help_text='CO2 emission per tonne fuel',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='co2_tax',
            field=models.PositiveIntegerField(
                help_text='CO2 tax (USD/t)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='fuel_density',
            field=models.FloatField(
                help_text='Fuel density (t/m3)',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='fuel_total_price',
            field=models.PositiveIntegerField(
                help_text='Total fuel price (USD/t)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='helicopter_avg_fuel_consumption',
            field=models.FloatField(
                help_text='Helicopter average fuel consumption (t/h)',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='helicopter_fuel_price',
            field=models.PositiveIntegerField(
                help_text='Helicopter fuel price (USD/t)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='helicopter_no_flights_per_week',
            field=models.FloatField(
                help_text='Helicopter number of flights per week',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='helicopter_rate_per_trip',
            field=models.FloatField(
                help_text='Helicopter rate per trip (USD)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='marine_diesel_oil_price',
            field=models.PositiveIntegerField(
                help_text='Marine Diesel oil price',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='nox_tax',
            field=models.PositiveIntegerField(
                help_text='NOX tag (USD/t)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='psv_avg_fuel_consumption',
            field=models.FloatField(
                help_text='Average PSV fuel consumption (t/d)',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='psv_calls_per_week',
            field=models.FloatField(
                help_text='PSV calls per week',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='psv_day_rate',
            field=models.FloatField(
                help_text='PSV day rate (USD)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='tugs_day_rate',
            field=models.FloatField(
                help_text='Tugs day rate (USD)', validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                help_text='Number of tugs to be used',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
