# Generated by Django 4.0.2 on 2022-05-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_alter_conceptwell_casing_data_and_more'),
        ('projects', '0006_planwellrelation_unique_plan_well_relation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planwellrelation',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='plan_wells', to='projects.plan'
            ),
        ),
        migrations.AlterField(
            model_name='planwellrelation',
            name='well',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='wells.customwell'
            ),
        ),
    ]
