# Generated by Django 4.0.2 on 2022-05-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_ahv_avg_fuel_consumption_and_more'),
        ('projects', '0006_planwellrelation_unique_plan_well_relation_order'),
    ]

    operations = []
