# Generated by Django 4.0.2 on 2022-05-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_planwellrelation_plan_and_more'),
        ('projects', '0007_merge_20220504_1342'),
    ]

    operations = []
