# Generated by Django 4.0.2 on 2022-05-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_jackup_rigs_alter_project_semi_rigs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project'
            ),
        ),
    ]
