# Generated by Django 4.0.2 on 2022-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0008_conceptdrillship_and_more'),
        ('projects', '0010_alter_plan_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drillships',
            field=models.ManyToManyField(blank=True, related_name='projects', to='rigs.CustomDrillship'),
        ),
    ]
