# Generated by Django 4.0.2 on 2022-05-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0009_alter_conceptwell_xt_running_tool_weight_and_more'),
        ('projects', '0011_project_drillships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wells',
            field=models.ManyToManyField(blank=True, related_name='unique_wells', to='wells.CustomWell'),
        ),
    ]
