# Generated by Django 4.0.2 on 2022-05-24 12:40

from django.db import migrations


def migrate_project(apps, *args):
    Project = apps.get_model('projects', 'Project')

    for project in Project.objects.all():
        for rig in project.semi_rigs.all():
            rig.project = project
            rig.save()
        for rig in project.jackup_rigs.all():
            rig.project = project
            rig.save()
        for rig in project.drillships.all():
            rig.project = project
            rig.save()
        for well in project.wells.all():
            well.project = project
            well.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_wells'),
        ('rigs', '0010_customdrillship_project_customjackuprig_project_and_more'),
        ('wells', '0010_customwell_project'),
    ]

    operations = [migrations.RunPython(migrate_project)]
