# Generated by Django 4.0.2 on 2022-05-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220524_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='drillships',
        ),
        migrations.RemoveField(
            model_name='project',
            name='jackup_rigs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='semi_rigs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wells',
        ),
    ]
