# Generated by Django 4.0.2 on 2022-06-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0011_alter_customwell_project'),
        ('projects', '0014_remove_project_drillships_remove_project_jackup_rigs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='wells',
            field=models.ManyToManyField(
                related_name='plans', through='projects.PlanWellRelation', to='wells.CustomWell'
            ),
        ),
        migrations.AlterField(
            model_name='planwellrelation',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.customwell'),
        ),
    ]
