# Generated by Django 4.0.2 on 2022-06-13 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20220609_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='distance_from_tug_base_to_previous_well',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Distance from Tug base to previous well (nm)',
            ),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('reference_operation_jackup__isnull', False),
                        ('reference_operation_semi__isnull', True),
                        ('reference_operation_drillship__isnull', True),
                    ),
                    models.Q(
                        ('reference_operation_jackup__isnull', True),
                        ('reference_operation_semi__isnull', False),
                        ('reference_operation_drillship__isnull', True),
                    ),
                    models.Q(
                        ('reference_operation_jackup__isnull', True),
                        ('reference_operation_semi__isnull', True),
                        ('reference_operation_drillship__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='single_reference_rig',
            ),
        ),
    ]
