# Generated by Django 4.0.2 on 2022-06-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_plan_wells_alter_planwellrelation_well'),
        ('projects', '0017_alter_plan_distance_from_tug_base_to_previous_well_and_more'),
    ]

    operations = []
