# Generated by Django 4.0.2 on 2022-06-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_plan_distance_from_tug_base_to_previous_well_and_more'),
        ('projects', '0018_merge_20220623_1031'),
    ]

    operations = []
