# Generated by Django 4.0.2 on 2022-06-14 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_plan_distance_from_tug_base_to_previous_well_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tugs_avg_fuel_consumption',
        ),
        migrations.AddField(
            model_name='project',
            name='tugs_avg_move_fuel_consumption',
            field=models.FloatField(
                default=20,
                help_text='Average Tug move fuel consumption (t/d)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tugs_avg_transit_fuel_consumption',
            field=models.FloatField(
                default=10,
                help_text='Average Tug transit fuel consumption (t/d)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
