# Generated by Django 4.0.2 on 2022-06-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_merge_20220623_1139'),
        ('projects', '0019_remove_project_tugs_avg_fuel_consumption_and_more'),
    ]

    operations = []
