# Generated by Django 4.0.2 on 2022-06-14 14:23

from django.db import migrations


def fix_values(apps, *args):
    Project = apps.get_model('projects', 'Project')

    Project.objects.filter(helicopter_cruise_speed__gt=40).update(helicopter_cruise_speed=40)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_planwellrelation_jackup_positioning_time_and_more'),
    ]

    operations = [migrations.RunPython(fix_values)]
