# Generated by Django 4.0.2 on 2022-06-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_merge_20220623_1152'),
        ('projects', '0021_auto_20220614_1423'),
    ]

    operations = []
