# Generated by Django 4.0.2 on 2022-06-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_helicopter_avg_fuel_consumption_and_more'),
        ('projects', '0022_merge_20220623_1200'),
    ]

    operations = []
