# Generated by Django 4.0.2 on 2022-06-28 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_merge_20220623_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='psv_fuel_price',
            field=models.PositiveIntegerField(
                default=2000,
                help_text='PSV fuel price (USD/t)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
            preserve_default=False,
        ),
    ]
