# Generated by Django 4.0.2 on 2022-06-30 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_psv_fuel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='helicopter_cruise_speed',
            field=models.FloatField(
                help_text='Cruise speed (kn)',
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
