# Generated by Django 4.0.2 on 2022-06-30 10:15

from django.db import migrations


def fix_helicopter_cruise_speed(apps, *args):
    Project = apps.get_model('projects', 'Project')

    Project.objects.update(helicopter_cruise_speed=120)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_project_helicopter_cruise_speed'),
    ]

    operations = [migrations.RunPython(fix_helicopter_cruise_speed)]
