# Generated by Django 4.0.2 on 2022-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_rigplanner_single_rig_planner_rig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptexternalsupply',
            name='energy',
            field=models.FloatField(help_text='Available energy per day in Kw/h'),
        ),
    ]
