# Generated by Django 4.0.2 on 2022-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_conceptexternalsupply_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigplanner',
            name='draft',
            field=models.BooleanField(
                default=False, help_text='Draft rig planners will not be visible in the application.'
            ),
            preserve_default=False,
        ),
    ]
