# Generated by Django 4.0.2 on 2022-09-08 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_rigplanner_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhelicopter',
            name='fuel_cost',
            field=models.FloatField(
                default=430, help_text='Fuel cost (USD/mT)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customhelicopter',
            name='nox',
            field=models.FloatField(
                default=25, help_text='NOX p/mT fuel (Kg)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customhelicopter',
            name='fuel',
            field=models.FloatField(
                help_text='Fuel consumption (Litres/h)', validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
