# Generated by Django 4.0.2 on 2022-09-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
        ('projects', '0032_auto_20220922_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcarboncapturestoragesystem',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='customcement',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='customexternalsupply',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='customhelicopter',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='customsteel',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='customvessel',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
    ]
