# Generated by Django 4.0.2 on 2022-10-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_rename_rig_planner_customcarboncapturestoragesystem_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='reference_operation_end_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='reference_operation_start_date',
        ),
    ]
