# Generated by Django 4.0.2 on 2022-10-10 08:48

from django.db import migrations, models


def migrate_vessel_type(apps, *args):
    CustomVessel = apps.get_model('projects', 'CustomVessel')
    for custom_vessel in CustomVessel.objects.all():
        custom_vessel.type = custom_vessel.vessel.name
        custom_vessel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_rename_rig_planner_customcarboncapturestoragesystem_asset_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customvessel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customvessel',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_vessel_type),
        migrations.RemoveField(
            model_name='customvessel',
            name='vessel',
        ),
        migrations.DeleteModel(
            name='ConceptVessel',
        ),
    ]
