# Generated by Django 4.0.2 on 2022-10-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_customvessel_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='customvessel',
                    name='asset',
                ),
            ]
        )
    ]
