# Generated by Django 4.0.2 on 2022-10-06 09:54

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_remove_plan_reference_operation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planwellrelation',
            name='operational_time',
            field=models.FloatField(
                default=20, help_text='Operational time (d)', validators=[apps.core.validators.GreaterThanValidator(0)]
            ),
        ),
    ]
