# Generated by Django 4.0.2 on 2022-10-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_remove_customvessel_asset'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.AlterModelTable('CustomVessel', 'emissions_customvessel')]
        )
    ]
