# Generated by Django 4.0.2 on 2022-10-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_planwellrelation_operational_time'),
        ('projects', '0038_delete_customvessel'),
    ]

    operations = []
