# Generated by Django 4.0.2 on 2022-10-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_delete_customvessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhelicopter',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
