# Generated by Django 4.0.2 on 2022-10-17 07:11

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_merge_20221014_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planwellrelation',
            name='operational_time',
            field=models.FloatField(
                help_text='Operational time (d)', validators=[apps.core.validators.GreaterThanValidator(0)]
            ),
        ),
    ]
