# Generated by Django 4.0.2 on 2022-10-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0020_vesseltype_deleted'),
        ('wells', '0044_alter_completevesseluse_unique_together_and_more'),
        ('projects', '0041_alter_customhelicopter_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomHelicopter',
            new_name='HelicopterType',
        ),
    ]
