# Generated by Django 4.0.2 on 2022-10-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        ('projects', '0044_auto_20221013_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helicoptertype',
            name='asset',
        ),
        migrations.AlterField(
            model_name='helicoptertype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
    ]
