# Generated by Django 4.0.2 on 2022-10-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_remove_helicoptertype_asset_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.AlterModelTable(name='HelicopterType', table='emissions_helicoptertype')]
        )
    ]
