# Generated by Django 4.0.2 on 2022-10-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0046_alter_completehelicopteruse_helicopter_type_and_more'),
        ('projects', '0046_rename_helicoptertype'),
        ('emissions', '0021_helicoptertype'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='HelicopterType',
                ),
            ]
        )
    ]
