# Generated by Django 4.0.2 on 2022-10-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_alter_planwellrelation_operational_time'),
        ('projects', '0047_delete_helicoptertype'),
    ]

    operations = []
