# Generated by Django 4.0.2 on 2022-10-26 08:43

from enum import Enum

from django.db import migrations


class MaterialCategoryEnum(str, Enum):
    STEEL = 'STEEL'
    CEMENT = 'CEMENT'


def migrate_custom_steel_to_material_type(CustomSteelModel, MaterialTypeModel):
    for custom_steel in CustomSteelModel.objects.all():
        material_type = MaterialTypeModel.objects.create(
            tenant=custom_steel.steel.tenant,
            category=MaterialCategoryEnum.STEEL,
            type=custom_steel.steel.name,
            unit='cubic metre',
            co2=custom_steel.co2,
        )
        custom_steel.material_type = material_type
        custom_steel.save()

        for well_planner_planned_step in custom_steel.wellplannerplannedstep_set.all():
            well_planner_planned_step.steel_material_type = material_type
            well_planner_planned_step.save()

        for well_planner_complete_step in custom_steel.wellplannercompletestep_set.all():
            well_planner_complete_step.steel_material_type = material_type
            well_planner_complete_step.save()


def migrate_custom_cement_to_material_type(CustomCementModel, MaterialTypeModel):
    for custom_cement in CustomCementModel.objects.all():
        material_type = MaterialTypeModel.objects.create(
            tenant=custom_cement.cement.tenant,
            category=MaterialCategoryEnum.CEMENT,
            type=custom_cement.cement.name,
            unit='tonne',
            co2=custom_cement.co2,
        )
        custom_cement.material_type = material_type
        custom_cement.save()

        for well_planner_planned_step in custom_cement.wellplannerplannedstep_set.all():
            well_planner_planned_step.cement_material_type = material_type
            well_planner_planned_step.save()

        for well_planner_complete_step in custom_cement.wellplannercompletestep_set.all():
            well_planner_complete_step.cement_material_type = material_type
            well_planner_complete_step.save()


def migrate_materials(apps, _):
    CustomSteelModel = apps.get_model('projects', 'CustomSteel')
    CustomCementModel = apps.get_model('projects', 'CustomCement')
    MaterialTypeModel = apps.get_model('emissions', 'MaterialType')

    migrate_custom_steel_to_material_type(CustomSteelModel, MaterialTypeModel)
    migrate_custom_cement_to_material_type(CustomCementModel, MaterialTypeModel)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_merge_20221017_0928'),
        ('emissions', '0031_materialtype'),
        ('wells', '0047_wellplannercompletestep_cement_material_type_and_more'),
        ('studies', '0018_auto_20221006_0851'),
    ]

    operations = [
        migrations.RunPython(migrate_materials, migrations.RunPython.noop),
    ]
