# Generated by Django 4.0.2 on 2022-10-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20221026_0843'),
        ('wells', '0048_remove_wellplannercompletestep_cement_material_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptsteel',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='customcement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customcement',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='customcement',
            name='cement',
        ),
        migrations.AlterUniqueTogether(
            name='customsteel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customsteel',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='customsteel',
            name='steel',
        ),
        migrations.DeleteModel(
            name='ConceptCement',
        ),
        migrations.DeleteModel(
            name='ConceptSteel',
        ),
        migrations.DeleteModel(
            name='CustomCement',
        ),
        migrations.DeleteModel(
            name='CustomSteel',
        ),
    ]
