# Generated by Django 4.0.2 on 2022-10-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_merge_20221020_1324'),
        ('wells', '0046_alter_completehelicopteruse_helicopter_type_and_more'),
        ('projects', '0051_alter_customexternalsupply_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomExternalSupply',
            new_name='ExternalEnergySupply',
        ),
        migrations.AlterModelOptions(
            name='externalenergysupply',
            options={'verbose_name': 'External Energy Supply', 'verbose_name_plural': 'External Energy Supplies'},
        ),
    ]
