# Generated by Django 4.0.2 on 2022-10-24 09:23

from django.db import migrations


def remove_duplicate_external_energy_supply(apps, *args):
    ExternalEnergySupply = apps.get_model('projects', 'ExternalEnergySupply')
    Asset = apps.get_model('emissions', 'Asset')

    for asset in Asset.objects.all():
        external_energy_supply = ExternalEnergySupply.objects.filter(asset=asset).order_by('id').first()
        if external_energy_supply:
            ExternalEnergySupply.objects.filter(asset=asset).exclude(pk=external_energy_supply.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_rename_customexternalsupply_externalenergysupply_and_more'),
        ('wells', '0048_alter_wellplannercompletestep_external_energy_supply_and_more'),
    ]

    operations = [migrations.RunPython(remove_duplicate_external_energy_supply)]
