# Generated by Django 4.0.2 on 2022-10-24 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_merge_20221020_1324'),
        ('projects', '0053_auto_20221024_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalenergysupply',
            name='energy',
        ),
        migrations.RenameField(model_name='externalenergysupply', old_name='name', new_name='type'),
        migrations.AddField(
            model_name='externalenergysupply',
            name='capacity',
            field=models.FloatField(
                default=0, help_text='Capacity (MWh/day)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalenergysupply',
            name='generator_efficiency_factor',
            field=models.FloatField(
                default=0,
                help_text='Generator efficiency factor (MWh/m3 fuel)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalenergysupply',
            name='nox',
            field=models.FloatField(
                default=0, help_text='Kg NOx / MWh', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalenergysupply',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='externalenergysupply',
            name='co2',
            field=models.FloatField(help_text='Ton CO2/MWh', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
