# Generated by Django 4.0.2 on 2022-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_remove_externalenergysupply_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalenergysupply',
            name='type',
            field=models.CharField(help_text='External energy supply type', max_length=255),
        ),
    ]
