# Generated by Django 4.0.2 on 2022-10-24 10:18

from django.db import migrations


def migrate_external_energy_supply_co2(apps, *args):
    ExternalEnergySupply = apps.get_model('projects', 'ExternalEnergySupply')

    for external_energy_supply in ExternalEnergySupply.objects.all():
        external_energy_supply.co2 = external_energy_supply.co2 / 1000
        external_energy_supply.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_alter_externalenergysupply_type'),
    ]

    operations = [migrations.RunPython(migrate_external_energy_supply_co2)]
