# Generated by Django 4.0.2 on 2022-10-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20221024_1018'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.AlterModelTable('ExternalEnergySupply', 'emissions_externalenergysupply')]
        ),
    ]
