# Generated by Django 4.0.2 on 2022-10-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_delete_externalenergysupply'),
        ('wells', '0050_alter_wellplannercompletestep_external_energy_supply_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ExternalEnergySupply',
                )
            ]
        )
    ]
