# Generated by Django 4.0.2 on 2022-11-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_remove_conceptsteel_tenant_and_more'),
        ('projects', '0058_delete_externalenergysupply'),
    ]

    operations = []
