# Generated by Django 4.0.2 on 2022-12-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_merge_20221107_0941'),
        ('wells', '0065_merge_20221130_1241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customcarboncapturestoragesystem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customcarboncapturestoragesystem',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='customcarboncapturestoragesystem',
            name='carbon_capture_storage_system',
        ),
        migrations.DeleteModel(
            name='ConceptCarbonCaptureStorageSystem',
        ),
        migrations.DeleteModel(
            name='CustomCarbonCaptureStorageSystem',
        ),
    ]
