# Generated by Django 4.0.2 on 2022-02-24 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConceptWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'type',
                    models.CharField(
                        choices=[('PRODUCTION', 'Production'), ('EXPLORATION', 'Exploration'), ('PNA', 'P&A')],
                        default='PRODUCTION',
                        max_length=16,
                    ),
                ),
                (
                    'top_hole',
                    models.CharField(
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        default=0,
                        max_length=16,
                        verbose_name='Top hole 36" & 26"',
                    ),
                ),
                (
                    'transport_section',
                    models.CharField(
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        default='SIMPLE',
                        max_length=16,
                        verbose_name='Transport section 17 1/2" & 12 1/4"',
                    ),
                ),
                (
                    'reservoir_section',
                    models.CharField(
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        default='SIMPLE',
                        max_length=16,
                        verbose_name='Reservoir section 8 1/2"',
                    ),
                ),
                (
                    'completion',
                    models.CharField(
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        default='SIMPLE',
                        max_length=16,
                        verbose_name='Completion',
                    ),
                ),
                (
                    'pna',
                    models.CharField(
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        default='SIMPLE',
                        max_length=16,
                        verbose_name='P&A',
                    ),
                ),
                (
                    'season',
                    models.CharField(
                        choices=[
                            ('YEARLY_AVERAGE', 'Yearly Average'),
                            ('SUMMER', 'Summer'),
                            ('WINTER', 'Winter'),
                            ('SPECIFIC', 'Specific'),
                        ],
                        default=0,
                        max_length=16,
                        verbose_name='Season',
                    ),
                ),
                (
                    'area',
                    models.CharField(
                        choices=[
                            ('GENERIC_NORTH_SEA', 'Generic North Sea'),
                            ('GENERIC_NORWEGIAN_SEA', 'Generic Norwegian Sea'),
                            ('GENERIC_BARENTS_SEA', 'Generic Barents Sea'),
                            ('CLIENT_SPECIFIC', 'Client Specific'),
                        ],
                        default='GENERIC_NORTH_SEA',
                        max_length=32,
                        verbose_name='Area',
                    ),
                ),
                (
                    'water_depth',
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Water depth (ft)',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
