# Generated by Django 4.0.2 on 2022-02-25 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptwell',
            name='area',
            field=models.CharField(
                choices=[
                    ('GENERIC_NORTH_SEA', 'Generic North Sea'),
                    ('GENERIC_NORWEGIAN_SEA', 'Generic Norwegian Sea'),
                    ('GENERIC_BARENTS_SEA', 'Generic Barents Sea'),
                    ('CLIENT_SPECIFIC', 'Client Specific'),
                ],
                max_length=32,
                verbose_name='Area',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='completion',
            field=models.CharField(
                choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                max_length=16,
                verbose_name='Completion',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='pna',
            field=models.CharField(
                choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                max_length=16,
                verbose_name='P&A',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='reservoir_section',
            field=models.CharField(
                choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                max_length=16,
                verbose_name='Reservoir section 8 1/2"',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='season',
            field=models.CharField(
                choices=[
                    ('YEARLY_AVERAGE', 'Yearly Average'),
                    ('SUMMER', 'Summer'),
                    ('WINTER', 'Winter'),
                    ('SPECIFIC', 'Specific'),
                ],
                max_length=16,
                verbose_name='Season',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='top_hole',
            field=models.CharField(
                choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                max_length=16,
                verbose_name='Top hole 36" & 26"',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='transport_section',
            field=models.CharField(
                choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                max_length=16,
                verbose_name='Transport section 17 1/2" & 12 1/4"',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='type',
            field=models.CharField(
                choices=[('PRODUCTION', 'Production'), ('EXPLORATION', 'Exploration'), ('PNA', 'P&A')], max_length=16
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='water_depth',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name='Water depth (ft)'
            ),
        ),
    ]
