# Generated by Django 4.0.2 on 2022-03-15 08:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_user_phone_number'),
        ('wells', '0002_alter_conceptwell_area_alter_conceptwell_completion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[('PRODUCTION', 'Production'), ('EXPLORATION', 'Exploration'), ('PNA', 'P&A')],
                        max_length=16,
                    ),
                ),
                (
                    'top_hole',
                    models.CharField(
                        blank=True,
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        max_length=16,
                        verbose_name='Top hole 36" & 26"',
                    ),
                ),
                (
                    'transport_section',
                    models.CharField(
                        blank=True,
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        max_length=16,
                        verbose_name='Transport section 17 1/2" & 12 1/4"',
                    ),
                ),
                (
                    'reservoir_section',
                    models.CharField(
                        blank=True,
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        max_length=16,
                        verbose_name='Reservoir section 8 1/2"',
                    ),
                ),
                (
                    'completion',
                    models.CharField(
                        blank=True,
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        max_length=16,
                        verbose_name='Completion',
                    ),
                ),
                (
                    'pna',
                    models.CharField(
                        blank=True,
                        choices=[('SIMPLE', 'Simple'), ('MEDIUM', 'Medium'), ('DEMANDING', 'Demanding')],
                        max_length=16,
                        verbose_name='P&A',
                    ),
                ),
                (
                    'season',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('YEARLY_AVERAGE', 'Yearly Average'),
                            ('SUMMER', 'Summer'),
                            ('WINTER', 'Winter'),
                            ('SPECIFIC', 'Specific'),
                        ],
                        max_length=16,
                        verbose_name='Season',
                    ),
                ),
                (
                    'area',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('GENERIC_NORTH_SEA', 'Generic North Sea'),
                            ('GENERIC_NORWEGIAN_SEA', 'Generic Norwegian Sea'),
                            ('GENERIC_BARENTS_SEA', 'Generic Barents Sea'),
                            ('CLIENT_SPECIFIC', 'Client Specific'),
                        ],
                        max_length=32,
                        verbose_name='Area',
                    ),
                ),
                (
                    'water_depth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='Water depth (ft)',
                    ),
                ),
                ('draft', models.BooleanField()),
                (
                    'creator',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
