# Generated by Django 4.0.2 on 2022-04-26 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_customwell'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptwell',
            name='casing_data',
            field=models.TextField(default='data', verbose_name='Casing data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='conductor_md_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor MD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='conductor_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor Size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='conductor_tvd_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor TVD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='conductor_weight',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor Weight (lbs/ft)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='expected_reservoir_pressure',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Expected reservoir pressure (bar)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='expected_reservoir_temperature',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Expected reservoir temperature (C)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='extension_section_hole_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Extension section hole size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='extension_section_mud_density',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Extension section mud density (10-3kg/m3)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='extension_section_mud_type',
            field=models.TextField(default='type', verbose_name='Extension section mud type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_md_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing MD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_section_hole_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing section hole size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_section_mud_density',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing section mud density (10-3kg/m3)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_section_mud_type',
            field=models.TextField(default='type', verbose_name='Intermediate casing section mud type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing Size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_tvd_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing TVD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='intermediate_casing_weight',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing Weight (lbs/ft)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='liner_other_md_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other MD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='liner_other_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other Size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='liner_other_tvd_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other TVD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='liner_other_weight',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other Weight (lbs/ft)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='lrp_lxbxh',
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='LRP, LxBxH (m)'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='lrp_weight',
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='LRP weight (t)'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='md_from_msl',
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MD from MSL (m)'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='metocean_data',
            field=models.TextField(default='data', verbose_name='Metocean data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='no_well_to_be_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='No. well to be completed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='planned_time_per_completion_operation',
            field=models.PositiveIntegerField(default=0, verbose_name='Planned time per completion operation (days)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='planned_time_per_well',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Planned time per well, d (time/depth curve)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_md_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing MD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_section_hole_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing section hole size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_section_mud_density',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing section mud density (10-3kg/m3)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_section_mud_type',
            field=models.TextField(default='type', verbose_name='Production casing section mud type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing Size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_tvd_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing TVD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='production_casing_weight',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing Weight (lbs/ft)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='subsea_xmas_tree_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Sub-sea X-mas tree size measured from centre of wellhead connector (+/- m) x H(m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='surface_casing_md_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing MD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='surface_casing_section_hole_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing section hole size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='surface_casing_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing Size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='surface_casing_tvd_shoe_depth',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing TVD shoe depth (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='surface_casing_weight',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing Weight (lbs/ft)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='top_hole_section_hole_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Top hole section hole size (inch)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='tvd_from_msl',
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TVD from MSL (m)'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='xt_running_tool_lxbxh',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='XT running tool, LxBxH (m)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='xt_running_tool_weight',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='XT running tool weight (t)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='xt_weight',
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='XT weight (t)'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customwell',
            name='casing_data',
            field=models.TextField(blank=True, verbose_name='Casing data'),
        ),
        migrations.AddField(
            model_name='customwell',
            name='conductor_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor MD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='conductor_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor Size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='conductor_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor TVD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='conductor_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor Weight (lbs/ft)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='expected_reservoir_pressure',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Expected reservoir pressure (bar)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='expected_reservoir_temperature',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Expected reservoir temperature (C)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='extension_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Extension section hole size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='extension_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Extension section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='extension_section_mud_type',
            field=models.TextField(blank=True, verbose_name='Extension section mud type'),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing MD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing section hole size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_section_mud_type',
            field=models.TextField(blank=True, verbose_name='Intermediate casing section mud type'),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing Size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing TVD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='intermediate_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing Weight (lbs/ft)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='liner_other_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other MD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='liner_other_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other Size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='liner_other_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other TVD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='liner_other_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other Weight (lbs/ft)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='lrp_lxbxh',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='LRP, LxBxH (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='lrp_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='LRP weight (t)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='md_from_msl',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='MD from MSL (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='metocean_data',
            field=models.TextField(blank=True, verbose_name='Metocean data'),
        ),
        migrations.AddField(
            model_name='customwell',
            name='no_well_to_be_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No. well to be completed'),
        ),
        migrations.AddField(
            model_name='customwell',
            name='planned_time_per_completion_operation',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Planned time per completion operation (days)'
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='planned_time_per_well',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Planned time per well, d (time/depth curve)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing MD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing section hole size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_section_mud_type',
            field=models.TextField(blank=True, verbose_name='Production casing section mud type'),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing Size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing TVD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='production_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing Weight (lbs/ft)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='subsea_xmas_tree_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Sub-sea X-mas tree size measured from centre of wellhead connector (+/- m) x H(m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='surface_casing_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing MD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='surface_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing section hole size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='surface_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing Size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='surface_casing_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing TVD shoe depth (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='surface_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing Weight (lbs/ft)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='top_hole_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Top hole section hole size (inch)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='tvd_from_msl',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='TVD from MSL (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='xt_running_tool_lxbxh',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='XT running tool, LxBxH (m)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='xt_running_tool_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='XT running tool weight (t)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='xt_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='XT weight (t)',
            ),
        ),
    ]
