# Generated by Django 4.0.2 on 2022-04-21 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_conceptwell_casing_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptwell',
            name='casing_data',
            field=models.TextField(blank=True, verbose_name='Casing data'),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor Size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Conductor Weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='expected_reservoir_pressure',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Expected reservoir pressure (bar)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='expected_reservoir_temperature',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Expected reservoir temperature (C)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='extension_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Extension section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='extension_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Extension section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='extension_section_mud_type',
            field=models.TextField(blank=True, verbose_name='Extension section mud type'),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_section_mud_type',
            field=models.TextField(blank=True, verbose_name='Intermediate casing section mud type'),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing Size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Intermediate casing Weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other Size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Liner/other Weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='md_from_msl',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='MD from MSL (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='planned_time_per_well',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Planned time per well, d (time/depth curve)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_section_mud_type',
            field=models.TextField(blank=True, verbose_name='Production casing section mud type'),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing Size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Production casing Weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing Size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Surface casing Weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='top_hole_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Top hole section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='tvd_from_msl',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='TVD from MSL (m)',
            ),
        ),
    ]
