# Generated by Django 4.0.2 on 2022-05-02 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_alter_conceptwell_casing_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptwell',
            name='area',
        ),
        migrations.RemoveField(
            model_name='conceptwell',
            name='casing_data',
        ),
        migrations.RemoveField(
            model_name='conceptwell',
            name='lrp_lxbxh',
        ),
        migrations.RemoveField(
            model_name='conceptwell',
            name='xt_running_tool_lxbxh',
        ),
        migrations.RemoveField(
            model_name='customwell',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customwell',
            name='casing_data',
        ),
        migrations.RemoveField(
            model_name='customwell',
            name='lrp_lxbxh',
        ),
        migrations.RemoveField(
            model_name='customwell',
            name='xt_running_tool_lxbxh',
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='lrp_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='LRP size (m3)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='metocean_days_above_hs_5',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)],
                verbose_name='Metocean days above HS 5',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptwell',
            name='xt_running_tool_size',
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='XT running tool, size (m3)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customwell',
            name='lrp_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='LRP size (m3)',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='metocean_days_above_hs_5',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)],
                verbose_name='Metocean days above HS 5',
            ),
        ),
        migrations.AddField(
            model_name='customwell',
            name='xt_running_tool_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='XT running tool, size (m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Conductor MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Conductor size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Conductor TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='conductor_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Conductor weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='expected_reservoir_pressure',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25000),
                ],
                verbose_name='Expected reservoir pressure (bar)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='expected_reservoir_temperature',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)],
                verbose_name='Expected reservoir temperature (C)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='extension_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Extension section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='extension_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
                verbose_name='Extension section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='extension_section_mud_type',
            field=models.CharField(
                blank=True,
                choices=[('OIL_BASED', 'Oil based'), ('WATER_BASED', 'Water based')],
                max_length=20,
                verbose_name='Extension section mud type',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Intermediate casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Intermediate casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
                verbose_name='Intermediate casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_section_mud_type',
            field=models.CharField(
                blank=True,
                choices=[('OIL_BASED', 'Oil based'), ('WATER_BASED', 'Water based')],
                max_length=20,
                verbose_name='Intermediate casing section mud type',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Intermediate casing size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Intermediate casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='intermediate_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Intermediate casing weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Liner/other MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Liner/other size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Liner/other TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='liner_other_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Liner/other weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='lrp_weight',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)],
                verbose_name='LRP weight (t)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='md_from_msl',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='MD from MSL (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='metocean_data',
            field=models.CharField(
                choices=[
                    ('GENERIC_NORTH_SEA', 'Generic North Sea'),
                    ('GENERIC_NORWEGIAN_SEA', 'Generic Norwegian Sea'),
                    ('GENERIC_BARENTS_SEA', 'Generic Barents Sea'),
                    ('CLIENT_SPECIFIC', 'Client specific'),
                ],
                max_length=30,
                verbose_name='Metocean data',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='no_well_to_be_completed',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='No. well to be completed',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='planned_time_per_completion_operation',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Planned time per completion operation (days)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='planned_time_per_well',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)],
                verbose_name='Planned time per well, d (time/depth curve)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Production casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Production casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
                verbose_name='Production casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_section_mud_type',
            field=models.CharField(
                blank=True,
                choices=[('OIL_BASED', 'Oil based'), ('WATER_BASED', 'Water based')],
                max_length=20,
                verbose_name='Production casing section mud type',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Production casing size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Production casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='production_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Production casing weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='subsea_xmas_tree_size',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='Sub-sea X-mas tree size (m3)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name='Surface casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Surface casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Surface casing size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name='Surface casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='surface_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Surface casing weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='top_hole_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Top hole section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='tvd_from_msl',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='TVD from MSL (m)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='water_depth',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name='Water depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='xt_running_tool_weight',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='XT running tool weight (t)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptwell',
            name='xt_weight',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                verbose_name='XT weight (t)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='conductor_md_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Conductor MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='conductor_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Conductor size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='conductor_tvd_shoe_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Conductor TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='conductor_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Conductor weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='expected_reservoir_pressure',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25000),
                ],
                verbose_name='Expected reservoir pressure (bar)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='expected_reservoir_temperature',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)],
                verbose_name='Expected reservoir temperature (C)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='extension_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Extension section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='extension_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
                verbose_name='Extension section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='extension_section_mud_type',
            field=models.CharField(
                blank=True,
                choices=[('OIL_BASED', 'Oil based'), ('WATER_BASED', 'Water based')],
                max_length=20,
                verbose_name='Extension section mud type',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Intermediate casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Intermediate casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
                verbose_name='Intermediate casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_section_mud_type',
            field=models.CharField(
                blank=True,
                choices=[('OIL_BASED', 'Oil based'), ('WATER_BASED', 'Water based')],
                max_length=20,
                verbose_name='Intermediate casing section mud type',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Intermediate casing size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Intermediate casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='intermediate_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Intermediate casing weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='liner_other_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Liner/other MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='liner_other_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Liner/other size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='liner_other_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Liner/other TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='liner_other_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Liner/other weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='lrp_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)],
                verbose_name='LRP weight (t)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='md_from_msl',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='MD from MSL (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='metocean_data',
            field=models.CharField(
                blank=True,
                choices=[
                    ('GENERIC_NORTH_SEA', 'Generic North Sea'),
                    ('GENERIC_NORWEGIAN_SEA', 'Generic Norwegian Sea'),
                    ('GENERIC_BARENTS_SEA', 'Generic Barents Sea'),
                    ('CLIENT_SPECIFIC', 'Client specific'),
                ],
                max_length=30,
                verbose_name='Metocean data',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='no_well_to_be_completed',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='No. well to be completed',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='planned_time_per_completion_operation',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Planned time per completion operation (days)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='planned_time_per_well',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)],
                verbose_name='Planned time per well, d (time/depth curve)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Production casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Production casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_section_mud_density',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
                verbose_name='Production casing section mud density (10-3kg/m3)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_section_mud_type',
            field=models.CharField(
                blank=True,
                choices=[('OIL_BASED', 'Oil based'), ('WATER_BASED', 'Water based')],
                max_length=20,
                verbose_name='Production casing section mud type',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Production casing size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='Production casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='production_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Production casing weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='subsea_xmas_tree_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='Sub-sea X-mas tree size (m3)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='surface_casing_md_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name='Surface casing MD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='surface_casing_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Surface casing section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='surface_casing_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Surface casing size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='surface_casing_tvd_shoe_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name='Surface casing TVD shoe depth (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='surface_casing_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name='Surface casing weight (lbs/ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='top_hole_section_hole_size',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Top hole section hole size (inch)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='tvd_from_msl',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
                verbose_name='TVD from MSL (m)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='water_depth',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
                verbose_name='Water depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='xt_running_tool_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='XT running tool weight (t)',
            ),
        ),
        migrations.AlterField(
            model_name='customwell',
            name='xt_weight',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)],
                verbose_name='XT weight (t)',
            ),
        ),
    ]
