# Generated by Django 4.0.2 on 2022-05-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_wells'),
        ('wells', '0009_alter_conceptwell_xt_running_tool_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customwell',
            name='project',
            field=models.ForeignKey(
                null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'
            ),
        ),
    ]
