# Generated by Django 4.0.2 on 2022-05-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_drillships_remove_project_jackup_rigs_and_more'),
        ('wells', '0010_customwell_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customwell',
            name='project',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wells',
                to='projects.project',
            ),
        ),
    ]
