# Generated by Django 4.0.2 on 2022-07-26 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0012_wellplanner_wellplannerstep_customvesseluse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhelicopteruse',
            name='well_planner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='custom_helicopter_uses',
                to='wells.wellplanner',
            ),
        ),
        migrations.AlterField(
            model_name='customvesseluse',
            name='days',
            field=models.FloatField(
                help_text='Days of operation',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='customvesseluse',
            name='well_planner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='custom_vessel_uses', to='wells.wellplanner'
            ),
        ),
    ]
