# Generated by Django 4.0.2 on 2022-07-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0012_wellplanner_wellplannerstep_customvesseluse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplannerstep',
            name='well_planner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='wells.wellplanner'
            ),
        ),
    ]
