# Generated by Django 4.0.2 on 2022-07-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0013_alter_customhelicopteruse_well_planner_and_more'),
        ('wells', '0013_alter_wellplannerstep_well_planner'),
    ]

    operations = []
