# Generated by Django 4.0.2 on 2022-08-16 08:03

import django.core.validators
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0016_completehelicopteruse_completevesseluse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completehelicopteruse',
            name='trips',
            field=models.IntegerField(
                help_text='Number of roundtrip flights', validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name='completevesseluse',
            name='days',
            field=models.FloatField(
                help_text='Days of operation',
                validators=[apps.core.validators.GreaterThanValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='plannedhelicopteruse',
            name='trips',
            field=models.IntegerField(
                help_text='Number of roundtrip flights', validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name='plannedvesseluse',
            name='days',
            field=models.FloatField(
                help_text='Days of operation',
                validators=[apps.core.validators.GreaterThanValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
