# Generated by Django 4.0.2 on 2022-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0018_alter_completehelicopteruse_fuel_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wellplannercompletestep',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('cement__isnull', True), ('cement_volume__isnull', True)),
                    models.Q(('cement__isnull', False), ('cement_volume__isnull', False)),
                    _connector='OR',
                ),
                name='well_planner_complete_step_cement_and_cement_volume_required_together',
            ),
        ),
        migrations.AddConstraint(
            model_name='wellplannercompletestep',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('steel__isnull', True), ('steel_weight__isnull', True)),
                    models.Q(('steel__isnull', False), ('steel_weight__isnull', False)),
                    _connector='OR',
                ),
                name='well_planner_complete_step_steel_and_steel_weight_required_together',
            ),
        ),
        migrations.AddConstraint(
            model_name='wellplannerplannedstep',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('cement__isnull', True), ('cement_volume__isnull', True)),
                    models.Q(('cement__isnull', False), ('cement_volume__isnull', False)),
                    _connector='OR',
                ),
                name='well_planner_planned_step_cement_and_cement_volume_required_together',
            ),
        ),
        migrations.AddConstraint(
            model_name='wellplannerplannedstep',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('steel__isnull', True), ('steel_weight__isnull', True)),
                    models.Q(('steel__isnull', False), ('steel_weight__isnull', False)),
                    _connector='OR',
                ),
                name='well_planner_planned_step_steel_and_steel_weight_required_together',
            ),
        ),
    ]
