# Generated by Django 4.0.2 on 2022-08-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        (
            'wells',
            '0019_wellplannercompletestep_well_planner_complete_step_cement_and_cement_volume_required_together_and_mo',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='WellReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.URLField(blank=True, help_text='Well details material')),
                ('vehicles', models.URLField(blank=True, help_text='Vessels & helicopters material')),
                ('planning', models.URLField(blank=True, help_text='Well planning material')),
                ('complete', models.URLField(blank=True, help_text='Well complete material')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
