# Generated by Django 4.0.2 on 2022-08-29 10:10

from django.db import migrations


def remove_duplicate_helicopter_vessel_uses(apps, _):
    PlannedHelicopterUseModel = apps.get_model('wells', 'PlannedHelicopterUse')
    PlannedVesselUseModel = apps.get_model('wells', 'PlannedVesselUse')
    CompleteHelicopterUseModel = apps.get_model('wells', 'CompleteHelicopterUse')
    CompleteVesselUseModel = apps.get_model('wells', 'CompleteVesselUse')

    PlannedHelicopterUseModel.objects.all().delete()
    PlannedVesselUseModel.objects.all().delete()
    CompleteHelicopterUseModel.objects.all().delete()
    CompleteVesselUseModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0020_wellreferencematerial'),
    ]

    operations = [migrations.RunPython(remove_duplicate_helicopter_vessel_uses, migrations.RunPython.noop)]
