# Generated by Django 4.0.2 on 2022-08-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_rigplanner_draft'),
        ('wells', '0021_auto_20220829_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completehelicopteruse',
            unique_together={('well_planner', 'helicopter')},
        ),
        migrations.AlterUniqueTogether(
            name='completevesseluse',
            unique_together={('well_planner', 'vessel')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedhelicopteruse',
            unique_together={('well_planner', 'helicopter')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedvesseluse',
            unique_together={('well_planner', 'vessel')},
        ),
    ]
