# Generated by Django 4.0.2 on 2022-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0022_alter_completehelicopteruse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplanner',
            name='current_step',
            field=models.CharField(
                choices=[
                    ('WELL_PLANNING', 'Well Planning'),
                    ('WELL_REVIEWING', 'Well Reviewing'),
                    ('WELL_REPORTING', 'Well Reporting'),
                ],
                max_length=32,
            ),
        ),
    ]
