# Generated by Django 4.0.2 on 2022-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0023_alter_wellplanner_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplanner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='side_track',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
