# Generated by Django 4.0.2 on 2022-09-12 10:26

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_rigplanner_draft'),
        ('wells', '0023_alter_wellplanner_current_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellPlannerPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                (
                    'rig_planner',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rigplanner'),
                ),
                (
                    'color',
                    colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
                ),
            ],
            options={
                'unique_together': {('rig_planner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WellPlannerMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                (
                    'rig_planner',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.rigplanner'),
                ),
            ],
            options={
                'unique_together': {('rig_planner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='mode_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='phase_model',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'
            ),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='mode_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='phase_model',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'
            ),
        ),
    ]
