# Generated by Django 4.0.2 on 2022-09-08 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0023_alter_wellplanner_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplanner',
            name='co2_tax',
            field=models.FloatField(
                default=0, help_text='CO2 tax (USD/mt)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='marine_diesel_oil_price',
            field=models.FloatField(
                default=0,
                help_text='Marine diesel oil price (USD/mt)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='nox_tax',
            field=models.FloatField(
                default=0, help_text='NOX tax (USD/mt)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
