# Generated by Django 4.0.2 on 2022-09-08 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0023_alter_wellplanner_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='well_section_length',
            field=models.FloatField(
                default=0,
                help_text='Well section length in meters',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='well_section_length',
            field=models.FloatField(
                default=0,
                help_text='Well section length in meters',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
