# Generated by Django 4.0.2 on 2022-09-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_wellplanner_co2_tax_and_more'),
        ('wells', '0024_wellplannercompletestep_well_section_length_and_more'),
    ]

    operations = []
