# Generated by Django 4.0.2 on 2022-09-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_wellplanner_description_wellplanner_side_track'),
        ('wells', '0025_merge_20220913_0751'),
    ]

    operations = []
