# Generated by Django 4.0.2 on 2022-09-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0026_alter_wellplannercompletestep_mode_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellplannercompletestep',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='wellplannercompletestep',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='wellplannerplannedstep',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='wellplannerplannedstep',
            name='phase',
        ),
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='mode_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='phase_model',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'
            ),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='mode_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='phase_model',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'
            ),
        ),
    ]
