# Generated by Django 4.0.2 on 2022-09-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_remove_wellplannercompletestep_operation_efficiencies_and_more'),
        ('wells', '0026_merge_20220913_0938'),
    ]

    operations = []
