# Generated by Django 4.0.2 on 2022-09-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0027_remove_wellplannercompletestep_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellplannercompletestep',
            old_name='mode_model',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='wellplannercompletestep',
            old_name='phase_model',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='wellplannerplannedstep',
            old_name='mode_model',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='wellplannerplannedstep',
            old_name='phase_model',
            new_name='phase',
        ),
    ]
