# Generated by Django 4.0.2 on 2022-09-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_alter_completevesseluse_unique_together_and_more'),
        ('wells', '0027_merge_20220913_1102'),
    ]

    operations = []
