# Generated by Django 4.0.2 on 2022-09-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0024_wellplannerplannedstep_waiting_on_weather'),
        ('wells', '0027_merge_20220913_1102'),
    ]

    operations = []
