# Generated by Django 4.0.2 on 2022-09-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0028_merge_20220913_1210'),
        ('wells', '0028_merge_20220913_1425'),
    ]

    operations = []
