# Generated by Django 4.0.2 on 2022-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0028_merge_20220913_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellplanner',
            old_name='start_date',
            new_name='planned_start_date',
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
