# Generated by Django 4.0.2 on 2022-09-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_rigplanner_draft'),
        ('wells', '0028_rename_mode_model_wellplannercompletestep_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wellplannermode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wellplannerphase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'),
        ),
        migrations.AlterField(
            model_name='wellplannermode',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='wellplannermode',
            name='rig_planner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='projects.rigplanner'
            ),
        ),
        migrations.AlterField(
            model_name='wellplannerphase',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='wellplannerphase',
            name='rig_planner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.rigplanner'
            ),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannermode'),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplannerphase'),
        ),
    ]
