# Generated by Django 4.0.2 on 2022-09-16 12:16

from django.db import migrations
from django.db.models import F


class WellPlannerWizardStep:
    WELL_REVIEWING = "WELL_REVIEWING"
    WELL_REPORTING = "WELL_REPORTING"


def migrate_actual_start_date(apps, *args):
    WellPlanner = apps.get_model('wells', 'WellPlanner')

    WellPlanner.objects.filter(
        current_step__in=[WellPlannerWizardStep.WELL_REVIEWING, WellPlannerWizardStep.WELL_REPORTING]
    ).update(actual_start_date=F('planned_start_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0029_rename_start_date_wellplanner_planned_start_date_and_more'),
    ]

    operations = [migrations.RunPython(migrate_actual_start_date)]
