# Generated by Django 4.0.2 on 2022-09-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0029_alter_conceptwell_tvd_from_msl'),
        ('wells', '0030_auto_20220916_1216'),
    ]

    operations = []
