# Generated by Django 4.0.2 on 2022-09-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0025_merge_20220913_0751'),
        ('wells', '0030_alter_wellplannermode_name_and_more'),
    ]

    operations = []
