# Generated by Django 4.0.2 on 2022-09-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0027_merge_20220913_1102'),
        ('wells', '0031_merge_20220913_0814'),
    ]

    operations = []
