# Generated by Django 4.0.2 on 2022-09-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0031_merge_20220921_0717'),
        ('wells', '0032_merge_20220914_0613'),
    ]

    operations = []
