# Generated by Django 4.0.2 on 2022-09-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
        ('projects', '0032_auto_20220922_0905'),
        ('wells', '0033_merge_20220921_0801'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='wellplanner',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='wellplannermode',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
        migrations.AlterField(
            model_name='wellplannerphase',
            name='rig_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
