# Generated by Django 4.0.2 on 2022-09-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0029_merge_20220914_0640'),
        ('wells', '0033_merge_20220921_0801'),
    ]

    operations = []
