# Generated by Django 4.0.2 on 2022-09-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_remove_asset_description_asset_design_description_and_more'),
        ('wells', '0034_alter_wellplanner_rig_planner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellplanner',
            old_name='rig_planner',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='wellplannermode',
            old_name='rig_planner',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='wellplannerphase',
            old_name='rig_planner',
            new_name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='wellplannermode',
            unique_together={('asset', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='wellplannerphase',
            unique_together={('asset', 'name')},
        ),
    ]
