# Generated by Django 4.0.2 on 2022-09-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0034_merge_20220923_1421'),
        ('wells', '0035_rename_rig_planner_wellplanner_asset_and_more'),
    ]

    operations = []
