# Generated by Django 4.0.2 on 2022-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0036_merge_20220926_0939'),
        ('emps', '0018_alter_customempinitiativephase_unique_together_and_more'),
        ('emissions', '0006_customempinitiative_customenergyuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='emp_initiatives',
            field=models.ManyToManyField(blank=True, to='emissions.CustomEmpInitiative'),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='emp_initiatives',
            field=models.ManyToManyField(blank=True, to='emissions.CustomEmpInitiative'),
        ),
    ]
