# Generated by Django 4.0.2 on 2022-09-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0009_baseline_unique_active_baseline'),
        ('wells', '0037_alter_wellplannercompletestep_emp_initiatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplanner',
            name='baseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.baseline'),
        ),
        migrations.AlterField(
            model_name='wellplanner',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.asset'),
        ),
    ]
