# Generated by Django 4.0.2 on 2022-09-28 08:53

from django.db import migrations


def set_baseline_for_well_planner(apps, *args):
    WellPlanner = apps.get_model('wells', 'WellPlanner')
    Baseline = apps.get_model('emissions', 'Baseline')

    for well_plan in WellPlanner.objects.all():
        well_plan.baseline = Baseline.objects.get(asset=well_plan.asset, active=True)
        well_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0038_wellplanner_baseline_alter_wellplanner_asset'),
        ('emissions', '0009_baseline_unique_active_baseline'),
    ]

    operations = [migrations.RunPython(set_baseline_for_well_planner)]
