# Generated by Django 4.0.2 on 2022-09-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0009_baseline_unique_active_baseline'),
        ('wells', '0039_auto_20220928_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplanner',
            name='baseline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.baseline'),
        ),
    ]
