# Generated by Django 4.0.2 on 2022-09-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0011_alter_baseline_asset'),
        ('wells', '0040_alter_wellplanner_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplanner',
            name='baseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.baseline'),
        ),
    ]
