# Generated by Django 4.0.2 on 2022-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0013_emissionmanagementplan_emissionreductioninitiative_and_more'),
        ('wells', '0041_alter_wellplanner_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='emp_initiatives',
            field=models.ManyToManyField(blank=True, to='emissions.EmissionReductionInitiative'),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='emp_initiatives',
            field=models.ManyToManyField(blank=True, to='emissions.EmissionReductionInitiative'),
        ),
    ]
