# Generated by Django 4.0.2 on 2022-10-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0013_customvessel'),
        ('wells', '0046_merge_20221012_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completevesseluse',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.customvessel'),
        ),
        migrations.AlterField(
            model_name='plannedvesseluse',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.customvessel'),
        ),
    ]
