# Generated by Django 4.0.2 on 2022-10-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0014_wellplannerphase_alter_baselineinput_phase_and_more'),
        ('wells', '0042_auto_20221004_0909'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.wellplannerphase'),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.wellplannerphase'),
        ),
        migrations.DeleteModel(
            name='WellPlannerPhase',
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations, database_operations=[])]
