# Generated by Django 4.0.2 on 2022-10-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0042_alter_completevesseluse_vessel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completevesseluse',
            old_name='vessel',
            new_name='vessel_type',
        ),
        migrations.RenameField(
            model_name='plannedvesseluse',
            old_name='vessel',
            new_name='vessel_type',
        ),
        migrations.AlterUniqueTogether(
            name='completevesseluse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plannedvesseluse',
            unique_together=set(),
        ),
    ]
