# Generated by Django 4.0.2 on 2022-09-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0016_remove_emissionreductioninitiative_asset_and_more'),
        ('wells', '0042_alter_wellplannercompletestep_emp_initiatives_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellplannercompletestep',
            old_name='emp_initiatives',
            new_name='emission_reduction_initiatives',
        ),
        migrations.RenameField(
            model_name='wellplannerplannedstep',
            old_name='emp_initiatives',
            new_name='emission_reduction_initiatives',
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='emission_management_plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='emissions.emissionmanagementplan',
            ),
        ),
    ]
