# Generated by Django 4.0.2 on 2022-09-30 11:27

from django.db import migrations


def migrate_emission_management_plan(apps, *args):
    WellPlanner = apps.get_model('wells', 'WellPlanner')
    EmissionManagementPlan = apps.get_model('emissions', 'EmissionManagementPlan')

    for well_planner in WellPlanner.objects.all():
        well_planner.emission_management_plan = EmissionManagementPlan.objects.filter(
            baseline=well_planner.baseline, active=True
        ).first()
        well_planner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0043_rename_emp_initiatives_wellplannercompletestep_emission_reduction_initiatives_and_more'),
        ('emissions', '0016_remove_emissionreductioninitiative_asset_and_more'),
    ]

    operations = [migrations.RunPython(migrate_emission_management_plan)]
