# Generated by Django 4.0.2 on 2022-10-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0019_rename_fuel_summer_vesseltype_fuel_consumption_summer_and_more'),
        ('wells', '0043_rename_vessel_completevesseluse_vessel_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completevesseluse',
            unique_together={('well_planner', 'vessel_type', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedvesseluse',
            unique_together={('well_planner', 'vessel_type', 'season')},
        ),
    ]
