# Generated by Django 4.0.2 on 2022-10-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0020_alter_baselineinput_mode_and_more'),
        ('wells', '0044_auto_20221005_0924'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.custommode'),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.custommode'),
        ),
        migrations.DeleteModel(name='WellPlannerMode'),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
