# Generated by Django 4.0.2 on 2022-10-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0044_auto_20220930_1127'),
        ('wells', '0045_alter_wellplannercompletestep_mode_and_more'),
    ]

    operations = []
