# Generated by Django 4.0.2 on 2022-10-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0031_materialtype'),
        ('wells', '0046_alter_completehelicopteruse_helicopter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='cement_material_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='well_planner_complete_step_cements',
                to='emissions.materialtype',
            ),
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='steel_material_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='well_planner_complete_step_steels',
                to='emissions.materialtype',
            ),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='cement_material_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='well_planner_planned_step_cements',
                to='emissions.materialtype',
            ),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='steel_material_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='well_planner_planned_step_steels',
                to='emissions.materialtype',
            ),
        ),
    ]
