# Generated by Django 4.0.2 on 2022-10-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_merge_20221020_1324'),
        ('wells', '0046_alter_completehelicopteruse_helicopter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplanner',
            name='baseline',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.baseline'
            ),
        ),
    ]
