# Generated by Django 4.0.2 on 2022-10-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_rename_customexternalsupply_externalenergysupply_and_more'),
        ('wells', '0047_rename_external_supply_wellplannercompletestep_external_energy_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='external_energy_supply',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.externalenergysupply'
            ),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='external_energy_supply',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.externalenergysupply'
            ),
        ),
    ]
