# Generated by Django 4.0.2 on 2022-10-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0047_alter_wellplanner_baseline'),
        ('wells', '0050_alter_wellplannercompletestep_external_energy_supply_and_more'),
    ]

    operations = []
