# Generated by Django 4.0.2 on 2022-11-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0048_remove_wellplannercompletestep_cement_material_type_and_more'),
        ('wells', '0051_merge_20221024_1139'),
    ]

    operations = []
