# Generated by Django 4.0.2 on 2022-11-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0040_alter_materialtype_category'),
        ('wells', '0052_merge_20221107_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='cement',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_cements',
                to='emissions.materialtype',
            ),
        ),
        migrations.AlterField(
            model_name='wellplannercompletestep',
            name='steel',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_steels',
                to='emissions.materialtype',
            ),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='cement',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_cements',
                to='emissions.materialtype',
            ),
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='steel',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_steels',
                to='emissions.materialtype',
            ),
        ),
    ]
