# Generated by Django 4.0.2 on 2022-11-10 11:01

from django.db import migrations


def remove_well_plans_without_baseline(apps, *args):
    WellPlanner = apps.get_model('wells', 'WellPlanner')

    WellPlanner.objects.filter(baseline=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0053_alter_wellplannercompletestep_cement_and_more'),
    ]

    operations = [migrations.RunPython(remove_well_plans_without_baseline)]
