# Generated by Django 4.0.2 on 2022-11-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0047_merge_20221110_1232'),
        ('wells', '0054_auto_20221110_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellplanner',
            name='baseline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.baseline'),
        ),
    ]
