# Generated by Django 4.0.2 on 2022-11-24 11:42

from django.db import migrations
from django.utils import timezone


def add_side_track(apps, *args):
    WellPlanner = apps.get_model('wells', 'WellPlanner')
    for well_planner in WellPlanner.objects.all():
        if not well_planner.side_track:
            well_planner.side_track = timezone.now().isoformat()
        if (
            WellPlanner.objects.filter(name=well_planner.name, side_track=well_planner.side_track)
            .exclude(pk=well_planner.pk)
            .exists()
        ):
            well_planner.side_track = timezone.now().isoformat()
        well_planner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0056_wellplanner_deleted'),
    ]

    operations = [migrations.RunPython(add_side_track)]
