# Generated by Django 4.0.2 on 2022-11-29 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0062_wellplannedstepmaterial_wellcompletestepmaterial'),
        ('wells', '0056_wellplanner_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='carbon_capture_storage_system_quantity',
            field=models.FloatField(
                help_text='CC&S quantity in Tons of CO2 per day',
                null=True,
                blank=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='external_energy_supply_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='material_types',
            field=models.ManyToManyField(
                related_name='complete_steps', through='emissions.WellCompleteStepMaterial', to='emissions.MaterialType'
            ),
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='external_energy_supply_quota',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplannercompletestep',
            name='waiting_on_weather',
            field=models.FloatField(
                default=0,
                help_text='Waiting on weather contingency for selected days in percentage',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='carbon_capture_storage_system_quantity',
            field=models.FloatField(
                help_text='CC&S quantity in Tons of CO2 per day',
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='external_energy_supply_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='material_types',
            field=models.ManyToManyField(
                related_name='planned_steps', through='emissions.WellPlannedStepMaterial', to='emissions.MaterialType'
            ),
        ),
        migrations.AddField(
            model_name='wellplannerplannedstep',
            name='external_energy_supply_quota',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wellplannerplannedstep',
            name='waiting_on_weather',
            field=models.FloatField(
                help_text='Waiting on weather contingency for selected days in percentage',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
