# Generated by Django 4.0.2 on 2022-11-29 12:19

from django.db import migrations


def migrate_well_planner_steps(WellPlannerStepModel, WellStepMaterialModel):
    for well_planner_step in WellPlannerStepModel.objects.all():
        if well_planner_step.external_energy_supply_id:
            well_planner_step.external_energy_supply_enabled = bool(well_planner_step.external_energy_supply_id)
            well_planner_step.save()

        if well_planner_step.carbon_capture_storage_system:
            well_planner_step.carbon_capture_storage_system_quantity = (
                well_planner_step.carbon_capture_storage_system.carbon_capture_storage_system.co2
            )
            well_planner_step.save()

        if well_planner_step.steel:
            WellStepMaterialModel.objects.create(
                step=well_planner_step,
                material_type=well_planner_step.steel,
                quantity=well_planner_step.steel_weight,
                quota=False,
            )

        if well_planner_step.cement:
            WellStepMaterialModel.objects.create(
                step=well_planner_step,
                material_type=well_planner_step.cement,
                quantity=well_planner_step.cement_volume,
                quota=False,
            )


def migrate(apps, _):
    WellPlannerPlannedStepModel = apps.get_model("wells", "WellPlannerPlannedStep")
    WellPlannedStepMaterialModel = apps.get_model("emissions", "WellPlannedStepMaterial")
    migrate_well_planner_steps(WellPlannerPlannedStepModel, WellPlannedStepMaterialModel)

    WellPlannerCompleteStepModel = apps.get_model("wells", "WellPlannerCompleteStep")
    WellCompleteStepMaterialModel = apps.get_model("emissions", "WellCompleteStepMaterial")
    migrate_well_planner_steps(WellPlannerCompleteStepModel, WellCompleteStepMaterialModel)


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0057_wellplannercompletestep_carbon_capture_storage_system_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
