# Generated by Django 4.0.2 on 2022-11-24 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0058_remove_wellplanner_type_wellplanner_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellplanner',
            name='marine_diesel_oil_price',
        ),
        migrations.RemoveField(
            model_name='wellplanner',
            name='operator',
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='co2_per_fuel',
            field=models.FloatField(
                default=3.17, help_text='Ton CO2/m3 fuel', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='fuel_cost',
            field=models.FloatField(
                default=800, help_text='Fuel cost (USD/m3)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='fuel_density',
            field=models.FloatField(
                default=850, help_text='Fuel density (kg/m3)', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='fuel_type',
            field=models.CharField(default='Marine diesel', help_text='Asset fuel type', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='nox_per_fuel',
            field=models.FloatField(
                default=52, help_text='Kg NOx/Ton fuel', validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='type',
            field=models.CharField(
                choices=[('EXPLORATION', 'Exploration'), ('PRODUCTION', 'Production'), ('APPRAISAL', 'Appraisal')],
                default='PRODUCTION',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='wellplanner',
            name='co2_tax',
            field=models.FloatField(
                help_text='CO2 tax (USD/m3)', validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='wellplanner',
            name='nox_tax',
            field=models.FloatField(
                help_text='NOx tax (USD/m3)', validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
