# Generated by Django 4.0.2 on 2022-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0059_remove_wellplanner_marine_diesel_oil_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellplanner',
            old_name='side_track',
            new_name='sidetrack',
        ),
        migrations.AlterField(
            model_name='wellplanner',
            name='type',
            field=models.CharField(
                choices=[('EXPLORATION', 'Exploration'), ('PRODUCTION', 'Production'), ('APPRAISAL', 'Appraisal')],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='wellplanner',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted', False)),
                fields=('name', 'sidetrack'),
                name='unique_well_planner_name_and_sidetrack',
            ),
        ),
    ]
