# Generated by Django 4.0.2 on 2022-11-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0062_wellname_wellname_unique_well_name'),
        ('wells', '0060_remove_wellplanner_unique_well_planner_name_and_side_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplanner',
            name='well_name',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.wellname'
            ),
        ),
    ]
