# Generated by Django 4.0.2 on 2022-11-28 09:48

from django.db import migrations


def migrate_well_name(apps, *args):
    WellName = apps.get_model('emissions', 'WellName')
    WellPlanner = apps.get_model('wells', 'WellPlanner')

    for well_planner in WellPlanner.objects.select_related('asset__tenant'):
        well_name, _ = WellName.objects.get_or_create(name=well_planner.name, tenant=well_planner.asset.tenant)
        well_planner.well_name = well_name
        well_planner.save()


class Migration(migrations.Migration):

    dependencies = [('wells', '0061_wellplanner_well_name'), ('emissions', '0062_wellname_wellname_unique_well_name')]

    operations = [migrations.RunPython(migrate_well_name)]
