# Generated by Django 4.0.2 on 2022-11-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0062_wellname_wellname_unique_well_name'),
        ('wells', '0062_auto_20221128_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellplanner',
            name='name',
        ),
        migrations.AlterField(
            model_name='wellplanner',
            name='well_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.wellname'),
        ),
    ]
