# Generated by Django 4.0.2 on 2022-11-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0063_remove_wellplanner_name_alter_wellplanner_well_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellplanner',
            old_name='well_name',
            new_name='name',
        ),
    ]
