# Generated by Django 4.0.2 on 2022-11-30 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0064_rename_well_name_wellplanner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellplanner',
            name='boilers_co2_per_fuel',
            field=models.FloatField(
                default=3.17,
                help_text='Ton CO2/m3 fuel for boilers',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellplanner',
            name='boilers_nox_per_fuel',
            field=models.FloatField(
                default=5,
                help_text='Kg NOx/Ton fuel for boilers',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
