# Generated by Django 4.0.2 on 2022-11-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'wells',
            '0059_remove_wellplannercompletestep_well_planner_complete_step_cement_and_cement_volume_required_together',
        ),
        ('wells', '0064_rename_well_name_wellplanner_name'),
    ]

    operations = []
