# Generated by Django 4.0.2 on 2022-12-01 07:37

import django.core.validators
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0064_rename_well_name_wellplanner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='completevesseluse',
            name='exposure_against_current_well',
            field=models.FloatField(
                default=100,
                help_text='Percentage exposure against current well',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completevesseluse',
            name='quota_obligation',
            field=models.FloatField(
                default=0,
                help_text='Percentage quota obligation',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completevesseluse',
            name='waiting_on_weather',
            field=models.FloatField(
                default=0,
                help_text='Waiting on weather contingency (%)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedvesseluse',
            name='exposure_against_current_well',
            field=models.FloatField(
                default=100,
                help_text='Percentage exposure against current well',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedvesseluse',
            name='quota_obligation',
            field=models.FloatField(
                default=0,
                help_text='Percentage quota obligation',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='plannedvesseluse',
            old_name='days',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='completevesseluse',
            old_name='days',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='completevesseluse',
            name='duration',
            field=models.FloatField(
                help_text='Duration (days)', validators=[apps.core.validators.GreaterThanValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='plannedvesseluse',
            name='duration',
            field=models.FloatField(
                help_text='Duration (days)', validators=[apps.core.validators.GreaterThanValidator(0)]
            ),
        ),
    ]
