# Generated by Django 4.0.2 on 2022-12-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0065_remove_completevesseluse_days_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completevesseluse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plannedvesseluse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='completevesseluse',
            name='well_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplanner'),
        ),
        migrations.AlterField(
            model_name='plannedvesseluse',
            name='well_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplanner'),
        ),
    ]
