# Generated by Django 4.0.2 on 2022-12-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0066_alter_completevesseluse_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='plannedvesseluse',
                    name='vessel_type',
                ),
                migrations.RemoveField(
                    model_name='plannedvesseluse',
                    name='well_planner',
                ),
                migrations.DeleteModel(
                    name='CompleteVesselUse',
                ),
                migrations.DeleteModel(
                    name='PlannedVesselUse',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='PlannedVesselUse',
                    table='emissions_plannedvesseluse',
                ),
                migrations.AlterModelTable(
                    name='CompleteVesselUse',
                    table='emissions_completevesseluse',
                ),
            ],
        )
    ]
