# Generated by Django 4.0.2 on 2022-12-05 09:35

import django.core.validators
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0067_remove_plannedvesseluse_vessel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completehelicopteruse',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='plannedhelicopteruse',
            name='fuel',
        ),
        migrations.AddField(
            model_name='completehelicopteruse',
            name='exposure_against_current_well',
            field=models.FloatField(
                default=100,
                help_text='Percentage exposure against current well',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completehelicopteruse',
            name='quota_obligation',
            field=models.FloatField(
                default=0,
                help_text='Percentage quota obligation',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedhelicopteruse',
            name='exposure_against_current_well',
            field=models.FloatField(
                default=100,
                help_text='Percentage exposure against current well',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedhelicopteruse',
            name='quota_obligation',
            field=models.FloatField(
                default=0,
                help_text='Percentage quota obligation',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completehelicopteruse',
            name='trip_duration',
            field=models.FloatField(
                help_text='Flight time per round trip (minutes)',
                validators=[apps.core.validators.GreaterThanValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='completehelicopteruse',
            name='trips',
            field=models.IntegerField(
                help_text='Number of round trips', validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name='plannedhelicopteruse',
            name='trip_duration',
            field=models.FloatField(
                help_text='Flight time per round trip (minutes)',
                validators=[apps.core.validators.GreaterThanValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='plannedhelicopteruse',
            name='trips',
            field=models.IntegerField(
                help_text='Number of round trips', validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name='completehelicopteruse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='plannedhelicopteruse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='completehelicopteruse',
            name='trip_duration',
            field=models.IntegerField(
                help_text='Flight time per round trip (minutes)',
                validators=[apps.core.validators.GreaterThanValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='plannedhelicopteruse',
            name='trip_duration',
            field=models.IntegerField(
                help_text='Flight time per round trip (minutes)',
                validators=[apps.core.validators.GreaterThanValidator(0)],
            ),
        ),
    ]
