# Generated by Django 4.0.2 on 2022-12-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0065_wellplanner_boilers_co2_per_fuel_and_more'),
        ('wells', '0067_remove_plannedvesseluse_vessel_type_and_more'),
    ]

    operations = []
