# Generated by Django 4.0.2 on 2022-12-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0065_merge_20221130_1241'),
        ('wells', '0068_merge_20221206_1425'),
    ]

    operations = []
