# Generated by Django 4.0.2 on 2022-12-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0068_remove_completehelicopteruse_fuel_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='plannedhelicopteruse',
                    name='helicopter_type',
                ),
                migrations.RemoveField(
                    model_name='plannedhelicopteruse',
                    name='well_planner',
                ),
                migrations.DeleteModel(
                    name='CompleteHelicopterUse',
                ),
                migrations.DeleteModel(
                    name='PlannedHelicopterUse',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(name='PlannedHelicopterUse', table='emissions_plannedhelicopteruse'),
                migrations.AlterModelTable(name='CompleteHelicopterUse', table='emissions_completehelicopteruse'),
            ],
        )
    ]
