# Generated by Django 4.0.2 on 2022-12-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0069_merge_20221206_1456'),
        ('wells', '0069_remove_plannedhelicopteruse_helicopter_type_and_more'),
    ]

    operations = []
