from apps.wells.models import AssetSeason, CustomWell, SimpleMediumDemanding, WellType

CUSTOM_WELL_PUBLIC_DATA = {
    "name": "Custom Well 1",
    "type": WellType.PRODUCTION,
    "top_hole": SimpleMediumDemanding.SIMPLE,
    "transport_section": SimpleMediumDemanding.DEMANDING,
    "reservoir_section": SimpleMediumDemanding.SIMPLE,
    "completion": SimpleMediumDemanding.SIMPLE,
    "pna": SimpleMediumDemanding.DEMANDING,
    "season": CustomWell.Season.YEARLY_AVERAGE,
    "metocean_data": CustomWell.MetoceanData.GENERIC_NORWEGIAN_SEA,
    "metocean_days_above_hs_5": 2.0,
    "water_depth": 100.0,
    "planned_time_per_well": 0.0,
    "tvd_from_msl": 0,
    "md_from_msl": 0,
    "expected_reservoir_pressure": 0,
    "expected_reservoir_temperature": 0.0,
    "top_hole_section_hole_size": 0.0,
    "surface_casing_section_hole_size": 0.0,
    "intermediate_casing_section_hole_size": 0.0,
    "production_casing_section_hole_size": 0.0,
    "extension_section_hole_size": 0.0,
    "intermediate_casing_section_mud_type": CustomWell.MudType.OIL_BASED,
    "production_casing_section_mud_type": CustomWell.MudType.OIL_BASED,
    "extension_section_mud_type": CustomWell.MudType.OIL_BASED,
    "intermediate_casing_section_mud_density": 0.0,
    "production_casing_section_mud_density": 0.0,
    "extension_section_mud_density": 0.0,
    "conductor_size": 0.0,
    "conductor_weight": 0.0,
    "conductor_tvd_shoe_depth": 0.0,
    "conductor_md_shoe_depth": 0.0,
    "surface_casing_size": 0.0,
    "surface_casing_weight": 0.0,
    "surface_casing_tvd_shoe_depth": 0.0,
    "surface_casing_md_shoe_depth": 0.0,
    "intermediate_casing_size": 0.0,
    "intermediate_casing_weight": 0.0,
    "intermediate_casing_tvd_shoe_depth": 0,
    "intermediate_casing_md_shoe_depth": 0,
    "production_casing_size": 0.0,
    "production_casing_weight": 0.0,
    "production_casing_tvd_shoe_depth": 0,
    "production_casing_md_shoe_depth": 0,
    "liner_other_size": 0.0,
    "liner_other_weight": 0.0,
    "liner_other_tvd_shoe_depth": 0,
    "liner_other_md_shoe_depth": 0,
    "no_well_to_be_completed": 0,
    "planned_time_per_completion_operation": 0,
    "subsea_xmas_tree_size": 0.0,
    "xt_weight": 1.0,
    "lrp_size": 0.0,
    "lrp_weight": 0.0,
    "xt_running_tool_size": 0.0,
    "xt_running_tool_weight": 0.0,
    "draft": False,
}

CUSTOM_WELL_DRAFT_DATA = {
    "name": "Draft Well 1",
    "type": "",
    "top_hole": "",
    "transport_section": "",
    "reservoir_section": "",
    "completion": "",
    "pna": "",
    "season": "",
    "water_depth": None,
    "metocean_data": "",
    "metocean_days_above_hs_5": None,
    "planned_time_per_well": None,
    "tvd_from_msl": None,
    "md_from_msl": None,
    "expected_reservoir_pressure": None,
    "expected_reservoir_temperature": None,
    "top_hole_section_hole_size": None,
    "surface_casing_section_hole_size": None,
    "intermediate_casing_section_hole_size": None,
    "production_casing_section_hole_size": None,
    "extension_section_hole_size": None,
    "intermediate_casing_section_mud_type": CustomWell.MudType.OIL_BASED,
    "production_casing_section_mud_type": CustomWell.MudType.OIL_BASED,
    "extension_section_mud_type": CustomWell.MudType.OIL_BASED,
    "intermediate_casing_section_mud_density": None,
    "production_casing_section_mud_density": None,
    "extension_section_mud_density": None,
    "conductor_size": None,
    "conductor_weight": None,
    "conductor_tvd_shoe_depth": None,
    "conductor_md_shoe_depth": None,
    "surface_casing_size": None,
    "surface_casing_weight": None,
    "surface_casing_tvd_shoe_depth": None,
    "surface_casing_md_shoe_depth": None,
    "intermediate_casing_size": None,
    "intermediate_casing_weight": None,
    "intermediate_casing_tvd_shoe_depth": None,
    "intermediate_casing_md_shoe_depth": None,
    "production_casing_size": None,
    "production_casing_weight": None,
    "production_casing_tvd_shoe_depth": None,
    "production_casing_md_shoe_depth": None,
    "liner_other_size": None,
    "liner_other_weight": None,
    "liner_other_tvd_shoe_depth": None,
    "liner_other_md_shoe_depth": None,
    "no_well_to_be_completed": None,
    "planned_time_per_completion_operation": None,
    "subsea_xmas_tree_size": None,
    "xt_weight": None,
    "lrp_size": None,
    "lrp_weight": None,
    "xt_running_tool_size": None,
    "xt_running_tool_weight": None,
    "draft": True,
}

WELL_PLANNER_PLANNED_STEP_DATA = {
    "duration": 50,
    "waiting_on_weather": 100,
    "season": AssetSeason.SUMMER,
    "carbon_capture_storage_system_quantity": 0,
    "well_section_length": 100,
    "external_energy_supply_enabled": False,
    "external_energy_supply_quota": False,
    "comment": "",
}

WELL_PLANNER_COMPLETE_STEP_DATA = {
    "duration": 100,
    "waiting_on_weather": 100,
    "season": AssetSeason.SUMMER,
    "carbon_capture_storage_system_quantity": 0,
    "well_section_length": 100,
    "external_energy_supply_enabled": False,
    "external_energy_supply_quota": False,
    "comment": "",
}
