# Generated by Django 4.0.2 on 2022-05-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                (
                    'tenant_user',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenantuserrelation'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
