# Generated by Django 4.0.2 on 2022-03-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target', models.FloatField()),
                ('baseline', models.FloatField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitors.monitor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
