# Generated by Django 4.0.2 on 2022-03-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitorelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorelement',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorelement',
            name='unit',
            field=models.CharField(default='Energy (MW)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitorelement',
            name='monitor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='monitors.monitor'
            ),
        ),
    ]
