# Generated by Django 4.0.2 on 2022-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_monitorelement_description_monitorelement_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorelement',
            old_name='unit',
            new_name='value_title',
        ),
        migrations.AddField(
            model_name='monitorelement',
            name='value_unit',
            field=models.CharField(default='MW', max_length=20),
            preserve_default=False,
        ),
    ]
