# Generated by Django 4.0.2 on 2022-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_rename_unit_monitorelement_value_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='draft',
            field=models.BooleanField(
                default=False, help_text='Draft monitors will not be visible in the application.'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorelement',
            name='draft',
            field=models.BooleanField(
                default=False, help_text='Draft monitor elements will not be visible in the application.'
            ),
            preserve_default=False,
        ),
    ]
