# Generated by Django 4.0.2 on 2022-05-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0001_initial'),
        ('monitors', '0005_monitor_draft_monitorelement_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kims.vessel'),
        ),
        migrations.AddField(
            model_name='monitorelement',
            name='monitor_function_source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitorelement',
            name='monitor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='monitors.monitor'
            ),
        ),
    ]
