# Generated by Django 4.0.2 on 2022-05-17 11:40

from django.db import migrations


def remove_monitors(apps, _):
    MonitorModel = apps.get_model('monitors', 'Monitor')
    MonitorModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_monitor_vessel_monitorelement_monitor_function'),
    ]

    operations = [
        migrations.RunPython(remove_monitors, migrations.RunPython.noop),
    ]
