# Generated by Django 4.0.2 on 2022-05-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0001_initial'),
        ('monitors', '0007_remove_monitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kims.vessel'),
        ),
        migrations.AlterField(
            model_name='monitorelement',
            name='monitor_function_source',
            field=models.TextField(verbose_name='Monitor function'),
        ),
    ]
