# Generated by Django 4.0.2 on 2022-05-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_alter_monitor_vessel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('baseline', models.FloatField()),
                ('target', models.FloatField()),
                ('date', models.DateField()),
                (
                    'monitor_element',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='values', to='monitors.monitorelement'
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='monitorelementvalue',
            constraint=models.UniqueConstraint(fields=('monitor_element', 'date'), name='unique_monitor_element_value'),
        ),
    ]
