# Generated by Django 4.0.2 on 2022-07-07 12:08

from django.db import migrations


def delete_monitoring_element_values(apps, *args):
    MonitorElementValue = apps.get_model('monitors', 'MonitorElementValue')

    MonitorElementValue.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0011_alter_monitor_end_date_alter_monitor_start_date_and_more'),
    ]

    operations = [migrations.RunPython(delete_monitoring_element_values)]
