# Generated by Django 4.0.2 on 2022-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0012_auto_20220707_1208'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monitorelementvalue',
            constraint=models.CheckConstraint(
                check=models.Q(('date__minute', 0), ('date__second', 0)), name='even_monitor_element_value_date_hour'
            ),
        ),
    ]
