# Generated by Django 4.0.2 on 2022-07-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0013_monitorelementvalue_even_monitor_element_value_date_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorElementPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(help_text='Phase start date')),
                ('end_date', models.DateField(help_text='Phase end date')),
                ('target', models.FloatField(help_text='Daily target')),
                ('baseline', models.FloatField(help_text='Daily baseline')),
                (
                    'monitor_element',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitorelement'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
