# Generated by Django 4.0.2 on 2022-07-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0015_auto_20220714_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorelement',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='monitorelement',
            name='target',
        ),
    ]
