# Generated by Django 4.0.2 on 2022-08-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0008_tagvalue_average'),
        ('monitors', '0016_remove_monitorelement_baseline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('draft', models.BooleanField(help_text="Draft functions won't be calculating values.")),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('CO2_EMISSION', 'CO2 emission'),
                            ('WIND_SPEED', 'Wind speed'),
                            ('AIR_TEMPERATURE', 'Air temperature'),
                            ('WAVE_HEAVE', 'Wave heave'),
                        ],
                        max_length=20,
                    ),
                ),
                ('monitor_function_source', models.TextField(verbose_name='Monitor function')),
                ('vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kims.vessel')),
                ('start_date', models.DateTimeField(help_text='Calculation start time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='monitorelement',
            name='monitor_function',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='monitor_elements',
                to='monitors.monitorfunction',
            ),
        ),
        migrations.AddField(
            model_name='monitorelementvalue',
            name='monitor_function',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='monitors.monitorfunction'
            ),
        ),
    ]
