# Generated by Django 4.0.2 on 2022-08-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0008_tagvalue_average'),
        ('monitors', '0018_auto_20220805_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorelement',
            name='monitor_function_source',
        ),
        migrations.AlterField(
            model_name='monitorelement',
            name='monitor_function',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='monitor_elements',
                to='monitors.monitorfunction',
            ),
        ),
        migrations.AlterField(
            model_name='monitorelementvalue',
            name='monitor_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitorfunction'),
        ),
        migrations.AlterField(
            model_name='monitorfunction',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kims.vessel'),
        ),
    ]
