# Generated by Django 4.0.2 on 2022-08-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0019_remove_monitorelement_monitor_function_source_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonitorElementValue',
            new_name='MonitorFunctionValue',
        ),
        migrations.RemoveConstraint(
            model_name='monitorfunctionvalue',
            name='unique_monitor_element_value',
        ),
        migrations.RemoveConstraint(
            model_name='monitorfunctionvalue',
            name='even_monitor_element_value_date_hour',
        ),
        migrations.AlterField(
            model_name='monitorfunctionvalue',
            name='monitor_element',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='values',
                to='monitors.monitorelement',
            ),
        ),
        migrations.AddConstraint(
            model_name='monitorfunctionvalue',
            constraint=models.UniqueConstraint(
                fields=('monitor_function', 'date'), name='unique_monitor_function_value'
            ),
        ),
        migrations.AddConstraint(
            model_name='monitorfunctionvalue',
            constraint=models.CheckConstraint(
                check=models.Q(('date__minute', 0), ('date__second', 0)), name='even_monitor_function_value_date_hour'
            ),
        ),
        migrations.RemoveField(
            model_name='monitorfunctionvalue',
            name='monitor_element',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='vessel',
        ),
    ]
