# Generated by Django 4.0.2 on 2022-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0020_monitorfunctionvalue_delete_monitorelementvalue_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monitorfunction',
            constraint=models.UniqueConstraint(
                condition=models.Q(('type', ''), _negated=True),
                fields=('vessel', 'type'),
                name='unique_together_monitor_function_vessel_type',
            ),
        ),
    ]
