# Generated by Django 4.0.2 on 2022-02-28 08:17

from django.db import migrations, models

import apps.tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.get_user_profile_image_path),
        ),
    ]
