# Generated by Django 4.0.2 on 2022-03-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_user_company_name_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('token', models.CharField(max_length=86)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
