# Generated by Django 4.0.2 on 2022-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantinvitation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenantinvitation',
            constraint=models.UniqueConstraint(fields=('tenant', 'token'), name='unique_tenant_invitation'),
        ),
    ]
