# Generated by Django 4.0.2 on 2022-03-24 14:40

from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_user_phone_number'),
    ]

    operations = [
        CryptoExtension(),
    ]
