# Generated by Django 4.0.2 on 2022-03-24 14:45

import django.contrib.auth.validators
import pgcrypto.fields
from django.db import migrations

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_auto_20220324_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=pgcrypto.fields.EncryptedEmailField(
                charset='utf-8', check_armor=True, cipher='aes', unique=True, versioned=False
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=pgcrypto.fields.EncryptedCharField(
                blank=True, charset='utf-8', check_armor=True, cipher='aes', verbose_name='first name', versioned=False
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=pgcrypto.fields.EncryptedCharField(
                blank=True, charset='utf-8', check_armor=True, cipher='aes', verbose_name='last name', versioned=False
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=pgcrypto.fields.EncryptedCharField(
                charset='utf-8',
                check_armor=True,
                cipher='aes',
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name='username',
                versioned=False,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.core.fields.EncryptedPhoneNumberField(
                blank=True,
                charset='utf-8',
                check_armor=True,
                cipher='aes',
                max_length=128,
                region=None,
                versioned=False,
            ),
        ),
    ]
