# Generated by Django 4.0.2 on 2022-03-24 14:27

from django.db import migrations


def encrypt_user_fields(apps, _):
    """
    We need to run save for all objects so that old values become ecrypted.
    """
    UserModel = apps.get_model('tenants', 'User')

    for user in UserModel.objects.all():
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [migrations.RunPython(encrypt_user_fields, migrations.RunPython.noop)]
