# Generated by Django 4.0.2 on 2022-11-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('ADMIN', 'Admin'), ('ASSET_MANAGER', 'Asset Manager'), ('OPERATOR', 'Operator')],
                default='ADMIN',
                max_length=24,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('company__isnull', False), ('role__in', ['ASSET_MANAGER', 'OPERATOR'])),
                    ('role', 'ADMIN'),
                    _connector='OR',
                ),
                name='optional_admin_company',
            ),
        ),
    ]
