# Generated by Django 4.0.2 on 2022-02-23 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rigs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptsemirig",
            name="draft",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(150),
                ],
                verbose_name="Draft (ft)",
            ),
        ),
    ]
