# Generated by Django 4.0.2 on 2022-03-14 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_user_phone_number'),
        ('rigs', '0003_conceptjackuprig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptsemirig',
            old_name='draft',
            new_name='draft_depth',
        )
    ]
