# Generated by Django 4.0.2 on 2022-03-15 07:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_user_phone_number'),
        ('rigs', '0004_rename_draft_conceptsemirig_draft_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSemiRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Manager')),
                ('design', models.CharField(blank=True, max_length=255, verbose_name='Design')),
                ('build_yard', models.CharField(blank=True, max_length=255, verbose_name='Build yard')),
                (
                    'rig_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('DRILLING', 'Drilling'),
                            ('UNDER_CONSTRUCTION', 'Under Construction'),
                            ('WARM_STACKED', 'Warm Stacked'),
                            ('COLD_STACKED', 'Cold Stacked'),
                            ('MOBILIZING', 'Mobilizing'),
                        ],
                        max_length=32,
                        verbose_name='Rig status',
                    ),
                ),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('special_survey_due', models.DateField(blank=True, null=True, verbose_name='Special survey date')),
                ('end_of_last_contract', models.DateField(blank=True, null=True, verbose_name='End of last contract')),
                (
                    'months_in_operation_last_year',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name='Months in operation last year',
                    ),
                ),
                (
                    'months_in_operation_last_3_years',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(36)],
                        verbose_name='Months in operation last 3 years',
                    ),
                ),
                (
                    'design_score',
                    models.CharField(
                        blank=True,
                        choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')],
                        max_length=16,
                        verbose_name='Design score',
                    ),
                ),
                (
                    'topside_design',
                    models.CharField(
                        blank=True,
                        choices=[('NOV', 'NOV'), ('MH', 'MH'), ('CAMERON', 'Cameron'), ('OTHER', 'Other')],
                        max_length=8,
                        verbose_name='Topside design',
                    ),
                ),
                (
                    'quarters_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(400),
                        ],
                        verbose_name='Quarters capacity',
                    ),
                ),
                (
                    'rig_water_depth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name='Rig water depth(ft)',
                    ),
                ),
                (
                    'variable_load',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Variable load (t)',
                    ),
                ),
                (
                    'hull_breadth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name='Hull breadth (ft)',
                    ),
                ),
                (
                    'hull_depth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='Hull depth (ft)',
                    ),
                ),
                (
                    'hull_length',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name='Hull length (ft)',
                    ),
                ),
                (
                    'derrick_height',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name='Derrick height (ft)',
                    ),
                ),
                (
                    'derrick_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(500000),
                            django.core.validators.MaxValueValidator(3000000),
                        ],
                        verbose_name='Derrick capacity (lbs)',
                    ),
                ),
                (
                    'drawworks_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name='Drawworks power (HP)',
                    ),
                ),
                (
                    'total_cranes',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Total cranes',
                    ),
                ),
                (
                    'crane_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name='Crane capacity',
                    ),
                ),
                (
                    'total_bop_rams',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Total BOP rams',
                    ),
                ),
                (
                    'bop_diamater_wp_max',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name='BOP diameter WP Max (in)',
                    ),
                ),
                (
                    'bop_wp_max',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5000),
                            django.core.validators.MaxValueValidator(25000),
                        ],
                        verbose_name='BOP WP Max (psi)',
                    ),
                ),
                (
                    'number_of_bop_stacks',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name='Number of bop stacks',
                    ),
                ),
                (
                    'mudpump_quantity',
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Mudpump quantity',
                    ),
                ),
                (
                    'liquid_mud',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(30000),
                        ],
                        verbose_name='Liquid mud (bbl)',
                    ),
                ),
                (
                    'mud_total_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Mud total (HP)',
                    ),
                ),
                (
                    'shaleshaker_total',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Shaleshaker total',
                    ),
                ),
                (
                    'engine_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Engine power (HP)',
                    ),
                ),
                (
                    'engine_quantity',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Engine quantity',
                    ),
                ),
                (
                    'engine_total',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    'generator_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Generator power (kW)',
                    ),
                ),
                (
                    'generator_quantity',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name='Generator quantity',
                    ),
                ),
                (
                    'generator_total',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name='Generator total',
                    ),
                ),
                (
                    'offline_stand_building',
                    models.BooleanField(blank=True, null=True, verbose_name='Offline stand building'),
                ),
                ('auto_pipe_handling', models.BooleanField(blank=True, null=True, verbose_name='Auto pipe handling')),
                ('dual_activity', models.BooleanField(blank=True, null=True, verbose_name='Dual activity')),
                ('drilltronic', models.BooleanField(blank=True, null=True, verbose_name='Drilltronic')),
                (
                    'dynamic_drilling_guide',
                    models.BooleanField(blank=True, null=True, verbose_name='Dynamic drilling guide'),
                ),
                (
                    'process_automation_platform',
                    models.BooleanField(blank=True, null=True, verbose_name='Process automation platform'),
                ),
                ('automatic_tripping', models.BooleanField(blank=True, null=True, verbose_name='Automatic tripping')),
                ('closed_bus', models.BooleanField(blank=True, null=True, verbose_name='Closed bus')),
                ('scr', models.BooleanField(blank=True, null=True, verbose_name='SCR')),
                ('hybrid', models.BooleanField(blank=True, null=True, verbose_name='Hybrid')),
                ('hvac_heat_recovery', models.BooleanField(blank=True, null=True, verbose_name='HVAC heat recovery')),
                (
                    'freshwater_cooling_systems',
                    models.BooleanField(blank=True, null=True, verbose_name='Freshwater cooling systems'),
                ),
                (
                    'seawater_cooling_systems',
                    models.BooleanField(blank=True, null=True, verbose_name='Seawater cooling systems'),
                ),
                (
                    'operator_awareness_dashboard',
                    models.BooleanField(blank=True, null=True, verbose_name='Operator awareness dashboard'),
                ),
                ('hpu_optimization', models.BooleanField(blank=True, null=True, verbose_name='HPU optimization')),
                (
                    'optimized_heat_tracing_system',
                    models.BooleanField(blank=True, null=True, verbose_name='Optimized heat tracing system'),
                ),
                (
                    'floodlighting_optimization',
                    models.BooleanField(blank=True, null=True, verbose_name='Floodlighting optimization'),
                ),
                (
                    'vfds_on_aux_machinery',
                    models.BooleanField(blank=True, null=True, verbose_name="VFD's on AUX machinery"),
                ),
                (
                    'equipment_load',
                    models.CharField(
                        blank=True,
                        choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')],
                        max_length=16,
                        verbose_name='Equipment load',
                    ),
                ),
                (
                    'drillfloor_efficiency',
                    models.CharField(
                        blank=True,
                        choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')],
                        max_length=16,
                        verbose_name='Drillfloor efficiency',
                    ),
                ),
                (
                    'hull_concept_score',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Hull concept score',
                    ),
                ),
                (
                    'hull_design_eco_score',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Hull design eco score',
                    ),
                ),
                ('dp', models.BooleanField(blank=True, null=True, verbose_name='DP')),
                (
                    'dp_class',
                    models.CharField(
                        blank=True,
                        choices=[('DP2', 'Dp2'), ('DP3', 'Dp3'), ('DP-ER', 'Dp Er')],
                        max_length=8,
                        verbose_name='DP Class',
                    ),
                ),
                ('thruster_assist', models.BooleanField(blank=True, null=True, verbose_name='Thruster assist')),
                (
                    'total_anchors',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(16),
                        ],
                        verbose_name='Total anchors',
                    ),
                ),
                ('anchor_standalone', models.BooleanField(blank=True, null=True, verbose_name='Anchor standalone')),
                (
                    'airgap',
                    models.CharField(
                        blank=True,
                        choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')],
                        max_length=16,
                        verbose_name='Airgap',
                    ),
                ),
                (
                    'draft_depth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name='Draft (ft)',
                    ),
                ),
                (
                    'displacement',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5000),
                            django.core.validators.MaxValueValidator(300000),
                        ],
                        verbose_name='Displacement',
                    ),
                ),
                ('dual_derrick', models.BooleanField(blank=True, null=True, verbose_name='Dual derrick')),
                (
                    'active_heave_drawwork',
                    models.BooleanField(blank=True, null=True, verbose_name='Active heave drawwork'),
                ),
                (
                    'cmc_with_active_heave',
                    models.BooleanField(blank=True, null=True, verbose_name='CMC with active heave'),
                ),
                ('ram_system', models.BooleanField(blank=True, null=True, verbose_name='RAM system')),
                ('tripsaver', models.BooleanField(blank=True, null=True, verbose_name='Tripsaver')),
                ('draft', models.BooleanField()),
                (
                    'creator',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomJackupRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Manager')),
                ('design', models.CharField(blank=True, max_length=255, verbose_name='Design')),
                ('build_yard', models.CharField(blank=True, max_length=255, verbose_name='Build yard')),
                (
                    'rig_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('DRILLING', 'Drilling'),
                            ('UNDER_CONSTRUCTION', 'Under Construction'),
                            ('WARM_STACKED', 'Warm Stacked'),
                            ('COLD_STACKED', 'Cold Stacked'),
                            ('MOBILIZING', 'Mobilizing'),
                        ],
                        max_length=32,
                        verbose_name='Rig status',
                    ),
                ),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('special_survey_due', models.DateField(blank=True, null=True, verbose_name='Special survey date')),
                ('end_of_last_contract', models.DateField(blank=True, null=True, verbose_name='End of last contract')),
                (
                    'months_in_operation_last_year',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name='Months in operation last year',
                    ),
                ),
                (
                    'months_in_operation_last_3_years',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(36)],
                        verbose_name='Months in operation last 3 years',
                    ),
                ),
                (
                    'design_score',
                    models.CharField(
                        blank=True,
                        choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')],
                        max_length=16,
                        verbose_name='Design score',
                    ),
                ),
                (
                    'topside_design',
                    models.CharField(
                        blank=True,
                        choices=[('NOV', 'NOV'), ('MH', 'MH'), ('CAMERON', 'Cameron'), ('OTHER', 'Other')],
                        max_length=8,
                        verbose_name='Topside design',
                    ),
                ),
                (
                    'quarters_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(400),
                        ],
                        verbose_name='Quarters capacity',
                    ),
                ),
                (
                    'rig_water_depth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name='Rig water depth(ft)',
                    ),
                ),
                (
                    'variable_load',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Variable load (t)',
                    ),
                ),
                (
                    'hull_breadth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name='Hull breadth (ft)',
                    ),
                ),
                (
                    'hull_depth',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='Hull depth (ft)',
                    ),
                ),
                (
                    'hull_length',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name='Hull length (ft)',
                    ),
                ),
                (
                    'derrick_height',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name='Derrick height (ft)',
                    ),
                ),
                (
                    'derrick_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(500000),
                            django.core.validators.MaxValueValidator(3000000),
                        ],
                        verbose_name='Derrick capacity (lbs)',
                    ),
                ),
                (
                    'drawworks_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name='Drawworks power (HP)',
                    ),
                ),
                (
                    'total_cranes',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Total cranes',
                    ),
                ),
                (
                    'crane_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name='Crane capacity',
                    ),
                ),
                (
                    'total_bop_rams',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Total BOP rams',
                    ),
                ),
                (
                    'bop_diamater_wp_max',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name='BOP diameter WP Max (in)',
                    ),
                ),
                (
                    'bop_wp_max',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5000),
                            django.core.validators.MaxValueValidator(25000),
                        ],
                        verbose_name='BOP WP Max (psi)',
                    ),
                ),
                (
                    'number_of_bop_stacks',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name='Number of bop stacks',
                    ),
                ),
                (
                    'mudpump_quantity',
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Mudpump quantity',
                    ),
                ),
                (
                    'liquid_mud',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(30000),
                        ],
                        verbose_name='Liquid mud (bbl)',
                    ),
                ),
                (
                    'mud_total_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Mud total (HP)',
                    ),
                ),
                (
                    'shaleshaker_total',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Shaleshaker total',
                    ),
                ),
                (
                    'engine_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Engine power (HP)',
                    ),
                ),
                (
                    'engine_quantity',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Engine quantity',
                    ),
                ),
                (
                    'engine_total',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    'generator_power',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20000),
                        ],
                        verbose_name='Generator power (kW)',
                    ),
                ),
                (
                    'generator_quantity',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name='Generator quantity',
                    ),
                ),
                (
                    'generator_total',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name='Generator total',
                    ),
                ),
                (
                    'offline_stand_building',
                    models.BooleanField(blank=True, null=True, verbose_name='Offline stand building'),
                ),
                ('auto_pipe_handling', models.BooleanField(blank=True, null=True, verbose_name='Auto pipe handling')),
                ('dual_activity', models.BooleanField(blank=True, null=True, verbose_name='Dual activity')),
                ('drilltronic', models.BooleanField(blank=True, null=True, verbose_name='Drilltronic')),
                (
                    'dynamic_drilling_guide',
                    models.BooleanField(blank=True, null=True, verbose_name='Dynamic drilling guide'),
                ),
                (
                    'process_automation_platform',
                    models.BooleanField(blank=True, null=True, verbose_name='Process automation platform'),
                ),
                ('automatic_tripping', models.BooleanField(blank=True, null=True, verbose_name='Automatic tripping')),
                ('closed_bus', models.BooleanField(blank=True, null=True, verbose_name='Closed bus')),
                ('scr', models.BooleanField(blank=True, null=True, verbose_name='SCR')),
                ('hybrid', models.BooleanField(blank=True, null=True, verbose_name='Hybrid')),
                ('hvac_heat_recovery', models.BooleanField(blank=True, null=True, verbose_name='HVAC heat recovery')),
                (
                    'freshwater_cooling_systems',
                    models.BooleanField(blank=True, null=True, verbose_name='Freshwater cooling systems'),
                ),
                (
                    'seawater_cooling_systems',
                    models.BooleanField(blank=True, null=True, verbose_name='Seawater cooling systems'),
                ),
                (
                    'operator_awareness_dashboard',
                    models.BooleanField(blank=True, null=True, verbose_name='Operator awareness dashboard'),
                ),
                ('hpu_optimization', models.BooleanField(blank=True, null=True, verbose_name='HPU optimization')),
                (
                    'optimized_heat_tracing_system',
                    models.BooleanField(blank=True, null=True, verbose_name='Optimized heat tracing system'),
                ),
                (
                    'floodlighting_optimization',
                    models.BooleanField(blank=True, null=True, verbose_name='Floodlighting optimization'),
                ),
                (
                    'vfds_on_aux_machinery',
                    models.BooleanField(blank=True, null=True, verbose_name="VFD's on AUX machinery"),
                ),
                (
                    'cantilevel_reach',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name='Cantilever reach (ft)',
                    ),
                ),
                (
                    'cantilevel_lateral',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name='Cantilever lateral (ft)',
                    ),
                ),
                (
                    'cantilever_capacity',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000),
                            django.core.validators.MaxValueValidator(5000000),
                        ],
                    ),
                ),
                (
                    'leg_length',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name='Leg length (ft)',
                    ),
                ),
                (
                    'leg_spacing',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name='Leg spacing (ft)',
                    ),
                ),
                ('subsea_drilling', models.BooleanField(blank=True, null=True, verbose_name='Subsea drilling')),
                ('enhanced_legs', models.BooleanField(blank=True, null=True, verbose_name='Enhanced legs')),
                ('draft', models.BooleanField()),
                (
                    'creator',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
