# Generated by Django 4.0.2 on 2022-04-26 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0005_alter_conceptjackuprig_end_of_last_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptjackuprig',
            name='rig_water_depth',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='Rig water depth(ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptsemirig',
            name='rig_water_depth',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(12000),
                ],
                verbose_name='Rig water depth(ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customjackuprig',
            name='rig_water_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)],
                verbose_name='Rig water depth(ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customsemirig',
            name='rig_water_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(12000),
                ],
                verbose_name='Rig water depth(ft)',
            ),
        ),
    ]
