# Generated by Django 4.0.2 on 2022-05-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0002_emp_rename_sub_area_conceptempelement_subarea_and_more'),
        ('rigs', '0006_alter_conceptjackuprig_rig_water_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customjackuprig',
            name='emp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emps.emp'),
        ),
        migrations.AddField(
            model_name='customsemirig',
            name='emp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emps.emp'),
        ),
    ]
