# Generated by Django 4.0.2 on 2022-05-23 09:53
import datetime

from django.db import migrations


def fix_dates(apps, *args):
    ConceptSemiRig = apps.get_model('rigs', 'ConceptSemiRig')
    CustomSemiRig = apps.get_model('rigs', 'CustomSemiRig')
    ConceptJackupRig = apps.get_model('rigs', 'ConceptJackupRig')
    CustomJackupRig = apps.get_model('rigs', 'CustomJackupRig')

    for Rig in [ConceptSemiRig, CustomSemiRig, ConceptJackupRig, CustomJackupRig]:
        Rig.objects.filter(delivery_date__lt=datetime.date(year=1970, month=1, day=1)).update(
            delivery_date=datetime.date(year=1970, month=1, day=1)
        )
        Rig.objects.filter(delivery_date__gt=datetime.date(year=2025, month=12, day=31)).update(
            delivery_date=datetime.date(year=2025, month=12, day=31)
        )
        Rig.objects.filter(special_survey_due__lt=datetime.date(year=2022, month=1, day=1)).update(
            special_survey_due=datetime.date(year=2022, month=1, day=1)
        )
        Rig.objects.filter(special_survey_due__gt=datetime.date(year=2027, month=12, day=31)).update(
            special_survey_due=datetime.date(year=2027, month=12, day=31)
        )
        Rig.objects.filter(end_of_last_contract__lt=datetime.date(year=1970, month=1, day=1)).update(
            end_of_last_contract=datetime.date(year=1970, month=1, day=1)
        )
        Rig.objects.filter(end_of_last_contract__gt=datetime.date(year=2035, month=12, day=31)).update(
            end_of_last_contract=datetime.date(year=2035, month=12, day=31)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0008_conceptdrillship_and_more'),
    ]

    operations = [migrations.RunPython(fix_dates)]
