# Generated by Django 4.0.2 on 2022-05-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_drillships_remove_project_jackup_rigs_and_more'),
        ('rigs', '0010_customdrillship_project_customjackuprig_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdrillship',
            name='project',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='drillships',
                to='projects.project',
            ),
        ),
        migrations.AlterField(
            model_name='customjackuprig',
            name='project',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='jackup_rigs',
                to='projects.project',
            ),
        ),
        migrations.AlterField(
            model_name='customsemirig',
            name='project',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='semi_rigs',
                to='projects.project',
            ),
        ),
    ]
