# Generated by Django 4.0.2 on 2022-06-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0011_alter_customdrillship_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptjackuprig',
            old_name='cantilevel_lateral',
            new_name='cantilever_lateral',
        ),
        migrations.RenameField(
            model_name='conceptjackuprig',
            old_name='cantilevel_reach',
            new_name='cantilever_reach',
        ),
        migrations.RenameField(
            model_name='customjackuprig',
            old_name='cantilevel_lateral',
            new_name='cantilever_lateral',
        ),
        migrations.RenameField(
            model_name='customjackuprig',
            old_name='cantilevel_reach',
            new_name='cantilever_reach',
        ),
    ]
