# Generated by Django 4.0.2 on 2022-06-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0012_rename_cantilevel_lateral_conceptjackuprig_cantilever_lateral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptdrillship',
            old_name='bop_diamater_wp_max',
            new_name='bop_diameter_wp_max',
        ),
        migrations.RenameField(
            model_name='conceptjackuprig',
            old_name='bop_diamater_wp_max',
            new_name='bop_diameter_wp_max',
        ),
        migrations.RenameField(
            model_name='conceptsemirig',
            old_name='bop_diamater_wp_max',
            new_name='bop_diameter_wp_max',
        ),
        migrations.RenameField(
            model_name='customdrillship',
            old_name='bop_diamater_wp_max',
            new_name='bop_diameter_wp_max',
        ),
        migrations.RenameField(
            model_name='customjackuprig',
            old_name='bop_diamater_wp_max',
            new_name='bop_diameter_wp_max',
        ),
        migrations.RenameField(
            model_name='customsemirig',
            old_name='bop_diamater_wp_max',
            new_name='bop_diameter_wp_max',
        ),
    ]
