# Generated by Django 4.0.2 on 2022-06-09 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0013_rename_bop_diamater_wp_max_conceptdrillship_bop_diameter_wp_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptdrillship',
            name='day_rate',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Day rate (USD/d)',
            ),
        ),
        migrations.AddField(
            model_name='conceptdrillship',
            name='spread_cost',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Spread cost (USD)',
            ),
        ),
        migrations.AddField(
            model_name='conceptdrillship',
            name='tugs_no_used',
            field=models.PositiveIntegerField(default=3, help_text='Number of tugs to be used'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptjackuprig',
            name='day_rate',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Day rate (USD/d)',
            ),
        ),
        migrations.AddField(
            model_name='conceptjackuprig',
            name='jack_down_time',
            field=models.FloatField(
                default=1.4,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Jack down to move time (d)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptjackuprig',
            name='jack_up_time',
            field=models.FloatField(
                default=1.4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jack up time (d)'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptjackuprig',
            name='spread_cost',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Spread cost (USD)',
            ),
        ),
        migrations.AddField(
            model_name='conceptjackuprig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(default=3, help_text='Number of tugs to be used'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptsemirig',
            name='day_rate',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Day rate (USD/d)',
            ),
        ),
        migrations.AddField(
            model_name='conceptsemirig',
            name='spread_cost',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Spread cost (USD)',
            ),
        ),
        migrations.AddField(
            model_name='conceptsemirig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(default=3, help_text='Number of tugs to be used'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customdrillship',
            name='day_rate',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Day rate (USD/d)',
            ),
        ),
        migrations.AddField(
            model_name='customdrillship',
            name='spread_cost',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Spread cost (USD)',
            ),
        ),
        migrations.AddField(
            model_name='customdrillship',
            name='tugs_no_used',
            field=models.PositiveIntegerField(default=3, help_text='Number of tugs to be used'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customjackuprig',
            name='day_rate',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Day rate (USD/d)',
            ),
        ),
        migrations.AddField(
            model_name='customjackuprig',
            name='jack_down_time',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Jack down to move time (d)',
            ),
        ),
        migrations.AddField(
            model_name='customjackuprig',
            name='jack_up_time',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Jack up time (d)',
            ),
        ),
        migrations.AddField(
            model_name='customjackuprig',
            name='spread_cost',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Spread cost (USD)',
            ),
        ),
        migrations.AddField(
            model_name='customjackuprig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(default=3, help_text='Number of tugs to be used'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customsemirig',
            name='day_rate',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Day rate (USD/d)',
            ),
        ),
        migrations.AddField(
            model_name='customsemirig',
            name='spread_cost',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Spread cost (USD)',
            ),
        ),
        migrations.AddField(
            model_name='customsemirig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(default=3, help_text='Number of tugs to be used'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptdrillship',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                help_text='Number of tugs to be used',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='conceptjackuprig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                help_text='Number of tugs to be used',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='conceptsemirig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                help_text='Number of tugs to be used',
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='customdrillship',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Number of tugs to be used',
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='customjackuprig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Number of tugs to be used',
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name='customsemirig',
            name='tugs_no_used',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Number of tugs to be used',
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
