# Generated by Django 4.0.2 on 2022-06-13 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0013_rename_bop_diamater_wp_max_conceptdrillship_bop_diameter_wp_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdrillship',
            name='number_of_bop_stacks',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name='Number of BOP stacks',
            ),
        ),
        migrations.AlterField(
            model_name='conceptjackuprig',
            name='number_of_bop_stacks',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name='Number of BOP stacks',
            ),
        ),
        migrations.AlterField(
            model_name='conceptsemirig',
            name='number_of_bop_stacks',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name='Number of BOP stacks',
            ),
        ),
        migrations.AlterField(
            model_name='customdrillship',
            name='number_of_bop_stacks',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name='Number of BOP stacks',
            ),
        ),
        migrations.AlterField(
            model_name='customjackuprig',
            name='number_of_bop_stacks',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name='Number of BOP stacks',
            ),
        ),
        migrations.AlterField(
            model_name='customsemirig',
            name='number_of_bop_stacks',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name='Number of BOP stacks',
            ),
        ),
    ]
