# Generated by Django 4.0.2 on 2022-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0013_rename_bop_diamater_wp_max_conceptdrillship_bop_diameter_wp_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdrillship',
            name='dp_class',
            field=models.CharField(
                choices=[('DP2', 'DP2'), ('DP3', 'DP3'), ('DP-ER', 'DP-ER')], max_length=8, verbose_name='DP Class'
            ),
        ),
        migrations.AlterField(
            model_name='conceptsemirig',
            name='dp_class',
            field=models.CharField(
                choices=[('DP2', 'DP2'), ('DP3', 'DP3'), ('DP-ER', 'DP-ER')], max_length=8, verbose_name='DP Class'
            ),
        ),
        migrations.AlterField(
            model_name='customdrillship',
            name='dp_class',
            field=models.CharField(
                blank=True,
                choices=[('DP2', 'DP2'), ('DP3', 'DP3'), ('DP-ER', 'DP-ER')],
                max_length=8,
                verbose_name='DP Class',
            ),
        ),
        migrations.AlterField(
            model_name='customsemirig',
            name='dp_class',
            field=models.CharField(
                blank=True,
                choices=[('DP2', 'DP2'), ('DP3', 'DP3'), ('DP-ER', 'DP-ER')],
                max_length=8,
                verbose_name='DP Class',
            ),
        ),
    ]
