# Generated by Django 4.0.2 on 2022-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0014_alter_conceptdrillship_dp_class_and_more'),
        ('rigs', '0014_alter_conceptdrillship_number_of_bop_stacks_and_more'),
    ]

    operations = []
