# Generated by Django 4.0.2 on 2022-06-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0014_customjackupsubareascore_customjackupplanco2_and_more'),
        ('rigs', '0015_merge_20220613_1119'),
    ]

    operations = []
