# Generated by Django 4.0.2 on 2022-06-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0014_conceptdrillship_day_rate_and_more'),
        ('rigs', '0016_merge_20220622_1446'),
    ]

    operations = []
