# Generated by Django 4.0.2 on 2022-06-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0015_alter_conceptdrillship_day_rate_and_more'),
        ('rigs', '0017_merge_20220623_1031'),
    ]

    operations = []
