# Generated by Django 4.0.2 on 2022-06-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0018_merge_20220623_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSemiSubareaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rig_status', models.FloatField()),
                ('topside_efficiency', models.FloatField()),
                ('deck_efficiency', models.FloatField()),
                ('wow', models.FloatField()),
                ('capacities', models.FloatField()),
                ('co2', models.FloatField()),
                (
                    'rig',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subarea_score',
                        to='rigs.customsemirig',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
