# Generated by Django 4.0.2 on 2022-06-23 15:21

from django.db import migrations


def add_missing_up_and_down_time(apps, *args):
    CustomJackupRig = apps.get_model('rigs', 'CustomJackupRig')

    CustomJackupRig.objects.filter(draft=False, jack_down_time__isnull=True).update(jack_down_time=1.4)
    CustomJackupRig.objects.filter(draft=False, jack_up_time__isnull=True).update(jack_up_time=1.4)


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0018_merge_20220623_1200'),
    ]

    operations = [migrations.RunPython(add_missing_up_and_down_time)]
