# Generated by Django 4.0.2 on 2022-06-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_merge_20220623_1200'),
        ('rigs', '0019_customsemisubareascore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSemiPlanCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helicopter_trips', models.FloatField(blank=True, help_text='Number of helicopter trips', null=True)),
                (
                    'helicopter_fuel',
                    models.FloatField(blank=True, help_text='Total helicopter fuel consumption (tons)', null=True),
                ),
                ('helicopter_cost', models.FloatField(blank=True, help_text='Total helicopter cost (USD)', null=True)),
                (
                    'helicopter_co2',
                    models.FloatField(blank=True, help_text='Helicopter CO2 emission (tons)', null=True),
                ),
                ('psv_trips', models.FloatField(blank=True, help_text='Number of PSV trips', null=True)),
                ('psv_fuel', models.FloatField(blank=True, help_text='Total PSV fuel consumption (tons)', null=True)),
                ('psv_cost', models.FloatField(blank=True, help_text='Total PSV CO2 cost (USD)', null=True)),
                ('psv_co2', models.FloatField(blank=True, help_text='Total PSV CO2 emission (tons)', null=True)),
                ('cost_per_day', models.FloatField(blank=True, help_text='Rig day rate (USD)', null=True)),
                ('total_fuel', models.FloatField(blank=True, help_text='Total fuel consumption (tons)', null=True)),
                ('total_cost', models.FloatField(blank=True, help_text='Total cost (USD)', null=True)),
                ('total_co2', models.FloatField(blank=True, help_text='Total CO2 emission (tons)', null=True)),
                ('ahv_fuel', models.FloatField(blank=True, help_text='Total AHV fuel consumption (tons)', null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plan')),
                (
                    'rig',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='co2_plans', to='rigs.customsemirig'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Custom Semi Plan CO2',
                'verbose_name_plural': "Custom Semi Plan CO2's",
            },
        ),
        migrations.AddConstraint(
            model_name='customsemiplanco2',
            constraint=models.UniqueConstraint(fields=('plan', 'rig'), name='unique_custom_semi_plan_co2'),
        ),
    ]
