# Generated by Django 4.0.2 on 2022-06-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0019_auto_20220623_1521'),
        ('rigs', '0020_customsemiplanco2_and_more'),
    ]

    operations = []
