# Generated by Django 4.0.2 on 2022-06-24 12:15

from django.db import migrations


def add_move_speed_to_semi(apps, *args):
    CustomSemiRig = apps.get_model('rigs', 'CustomSemiRig')

    CustomSemiRig.objects.filter(draft=False, move_speed__isnull=True).update(move_speed=6.0)


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0020_conceptsemirig_move_speed_customsemirig_move_speed'),
    ]

    operations = [migrations.RunPython(add_move_speed_to_semi)]
