# Generated by Django 4.0.2 on 2022-06-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0021_auto_20220624_1215'),
        ('rigs', '0021_merge_20220630_0940'),
    ]

    operations = []
