# Generated by Django 4.0.2 on 2022-06-30 10:29

from django.db import migrations


def fix_move_speed_for_semi(apps, *args):
    CustomSemiRig = apps.get_model('rigs', 'CustomSemiRig')
    ConceptSemiRig = apps.get_model('rigs', 'ConceptSemiRig')

    ConceptSemiRig.objects.filter(dp=True).update(move_speed=6.0)
    ConceptSemiRig.objects.filter(dp=False).update(move_speed=0.0)
    CustomSemiRig.objects.filter(draft=False, dp=True).update(move_speed=6.0)
    CustomSemiRig.objects.filter(draft=False, dp=False).update(move_speed=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0021_auto_20220624_1215'),
    ]

    operations = [migrations.RunPython(fix_move_speed_for_semi)]
