# Generated by Django 4.0.2 on 2022-06-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0022_auto_20220630_1029'),
        ('rigs', '0022_merge_20220630_1022'),
    ]

    operations = []
