# Generated by Django 4.0.2 on 2022-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0023_merge_20220630_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customjackupplanco2',
            name='cost_per_day',
        ),
        migrations.RemoveField(
            model_name='customsemiplanco2',
            name='ahv_fuel',
        ),
        migrations.RemoveField(
            model_name='customsemiplanco2',
            name='cost_per_day',
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='ahv_cost',
            field=models.FloatField(blank=True, help_text='Total AHV cost (USD)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='total_fuel_cost',
            field=models.FloatField(blank=True, help_text='Total fuel cost (USD)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='total_logistic_cost',
            field=models.FloatField(blank=True, help_text='Total logistic cost (USD)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='total_move_cost',
            field=models.FloatField(blank=True, help_text='Total move cost (USD)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='total_rig_and_spread_cost',
            field=models.FloatField(blank=True, help_text='Total rig and spread cost (USD)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='total_support_co2',
            field=models.FloatField(blank=True, help_text='Total support CO2 emission (tons)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='total_transit_co2',
            field=models.FloatField(blank=True, help_text='Total transit CO2 emission (tons)', null=True),
        ),
        migrations.AddField(
            model_name='customsemiplanco2',
            name='tugs_cost',
            field=models.FloatField(blank=True, help_text='Total tugs cost (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='customjackupplanco2',
            name='helicopter_co2',
            field=models.FloatField(blank=True, help_text='Total Helicopter CO2 emission (tons)', null=True),
        ),
        migrations.AlterField(
            model_name='customsemiplanco2',
            name='helicopter_co2',
            field=models.FloatField(blank=True, help_text='Total Helicopter CO2 emission (tons)', null=True),
        ),
    ]
