# Generated by Django 4.0.2 on 2022-07-08 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0024_remove_customjackupplanco2_cost_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdrillship',
            name='hull_depth',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name='Hull depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptjackuprig',
            name='hull_depth',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name='Hull depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='conceptsemirig',
            name='hull_depth',
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name='Hull depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customdrillship',
            name='hull_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name='Hull depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customjackuprig',
            name='hull_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name='Hull depth (ft)',
            ),
        ),
        migrations.AlterField(
            model_name='customsemirig',
            name='hull_depth',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name='Hull depth (ft)',
            ),
        ),
    ]
