# Generated by Django 4.0.2 on 2022-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0026_customjackupplanco2_cost_per_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customjackupplanco2',
            name='cost_per_meter',
            field=models.FloatField(blank=True, help_text='Cost per meter (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='customsemiplanco2',
            name='cost_per_meter',
            field=models.FloatField(blank=True, help_text='Cost per meter (USD)', null=True),
        ),
    ]
