# Generated by Django 4.0.2 on 2022-10-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0028_customjackupplanco2_total_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customjackupplanco2',
            name='total_days',
            field=models.FloatField(blank=True, help_text='Total days', null=True),
        ),
        migrations.AlterField(
            model_name='customsemiplanco2',
            name='total_days',
            field=models.FloatField(blank=True, help_text='Total days', null=True),
        ),
    ]
