# Generated by Django 4.0.2 on 2022-05-13 06:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the FAQ section', max_length=255, unique=True)),
                ('draft', models.BooleanField(help_text='Draft FAQs will not be visible in the app')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', ckeditor.fields.RichTextField()),
                ('draft', models.BooleanField(help_text='Draft questions will not be visible in the app')),
                (
                    'faq',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='support.faq'
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='faqelement',
            constraint=models.UniqueConstraint(fields=('faq', 'question'), name='unique_faq_element'),
        ),
    ]
