# Generated by Django 4.0.2 on 2022-05-04 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_plan_planwellrelation_plan_wells_and_more'),
        ('rigs', '0006_alter_conceptjackuprig_rig_water_depth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                (
                    'creator',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudyElementSemiRigRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rigs.customsemirig')),
                (
                    'study_element',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studies.studyelement'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='StudyElementJackupRigRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rigs.customjackuprig')),
                (
                    'study_element',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studies.studyelement'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='studyelement',
            name='jackup_rigs',
            field=models.ManyToManyField(
                blank=True, through='studies.StudyElementJackupRigRelation', to='rigs.CustomJackupRig'
            ),
        ),
        migrations.AddField(
            model_name='studyelement',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studies.studymetric'),
        ),
        migrations.AddField(
            model_name='studyelement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.plan'),
        ),
        migrations.AddField(
            model_name='studyelement',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='study_elements', to='projects.project'
            ),
        ),
        migrations.AddField(
            model_name='studyelement',
            name='semi_rigs',
            field=models.ManyToManyField(
                blank=True, through='studies.StudyElementSemiRigRelation', to='rigs.CustomSemiRig'
            ),
        ),
        migrations.AddConstraint(
            model_name='studyelementsemirigrelation',
            constraint=models.UniqueConstraint(
                fields=('study_element', 'rig'), name='unique_study_element_semi_rig_relation'
            ),
        ),
        migrations.AddConstraint(
            model_name='studyelementjackuprigrelation',
            constraint=models.UniqueConstraint(
                fields=('study_element', 'rig'), name='unique_study_element_jackup_rig_relation'
            ),
        ),
    ]
