# Generated by Django 4.0.2 on 2022-05-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20220504_1342'),
        ('rigs', '0006_alter_conceptjackuprig_rig_water_depth_and_more'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyelement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plan'),
        ),
        migrations.AlterField(
            model_name='studyelement',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='study_elements', to='projects.project'
            ),
        ),
        migrations.AlterField(
            model_name='studyelementjackuprigrelation',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigs.customjackuprig'),
        ),
        migrations.AlterField(
            model_name='studyelementjackuprigrelation',
            name='study_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.studyelement'),
        ),
        migrations.AlterField(
            model_name='studyelementsemirigrelation',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigs.customsemirig'),
        ),
        migrations.AlterField(
            model_name='studyelementsemirigrelation',
            name='study_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.studyelement'),
        ),
    ]
