# Generated by Django 4.0.2 on 2022-05-05 11:12

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_studyelement_plan_alter_studyelement_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyelement',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AddConstraint(
            model_name='studyelement',
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable['DEFERRED'],
                fields=('project', 'order'),
                name='unique_study_element_order',
            ),
        ),
    ]
