# Generated by Django 4.0.2 on 2022-05-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_plan_project'),
        ('studies', '0003_alter_studyelement_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
