# Generated by Django 4.0.2 on 2022-06-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_plan_wells_alter_planwellrelation_well'),
        ('rigs', '0014_customjackupsubareascore_customjackupplanco2_and_more'),
        ('studies', '0005_studyelementdrillshiprelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyelementjackuprigrelation',
            name='rig_plan_co2',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='rigs.customjackupplanco2'
            ),
        ),
        migrations.AddField(
            model_name='studymetric',
            name='key',
            field=models.CharField(help_text='Rig CO2 plan attribute field name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyelement',
            name='jackup_rigs',
            field=models.ManyToManyField(
                blank=True,
                related_name='study_elements',
                through='studies.StudyElementJackupRigRelation',
                to='rigs.CustomJackupRig',
            ),
        ),
        migrations.AlterField(
            model_name='studyelement',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='study_elements', to='projects.plan'
            ),
        ),
        migrations.AlterField(
            model_name='studyelementdrillshiprelation',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studyelementjackuprigrelation',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studyelementsemirigrelation',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studymetric',
            name='name',
            field=models.CharField(help_text='Display name of the metric', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studymetric',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
