# Generated by Django 4.0.2 on 2022-06-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0014_customjackupsubareascore_customjackupplanco2_and_more'),
        ('studies', '0007_auto_20220622_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyelementjackuprigrelation',
            name='rig_plan_co2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigs.customjackupplanco2'),
        ),
        migrations.AlterField(
            model_name='studymetric',
            name='key',
            field=models.CharField(help_text='Rig CO2 plan attribute field name', max_length=100, unique=True),
        ),
    ]
