# Generated by Django 4.0.2 on 2022-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0020_customsemiplanco2_and_more'),
        ('studies', '0008_alter_studyelementjackuprigrelation_rig_plan_co2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyelement',
            name='semi_rigs',
            field=models.ManyToManyField(
                blank=True,
                related_name='study_elements',
                through='studies.StudyElementSemiRigRelation',
                to='rigs.CustomSemiRig',
            ),
        ),
    ]
