# Generated by Django 4.0.2 on 2022-06-24 10:42

from django.db import migrations


def create_default_custom_semi_plan_co2(apps, _):
    StudyElementSemiRelationModel = apps.get_model('studies', 'StudyElementSemiRigRelation')
    StudyElementSemiRelationModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_studyelementsemirigrelation_rig_plan_co2'),
    ]

    operations = [migrations.RunPython(create_default_custom_semi_plan_co2, migrations.RunPython.noop)]
