# Generated by Django 4.0.2 on 2022-06-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigs', '0020_customsemiplanco2_and_more'),
        ('studies', '0011_auto_20220624_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyelementsemirigrelation',
            name='rig_plan_co2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigs.customsemiplanco2'),
        ),
    ]
