# Generated by Django 4.0.2 on 2022-07-01 14:12

from django.db import migrations


def delete_study_element_drillship_relation(apps, *args):
    StudyElementDrillshipRelation = apps.get_model('studies', 'StudyElementDrillshipRelation')
    StudyElementDrillshipRelation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_studyelementsemirigrelation_rig_plan_co2'),
    ]

    operations = [migrations.RunPython(delete_study_element_drillship_relation)]
