# Generated by Django 4.0.2 on 2022-06-30 14:12

from django.db import migrations

METRICS_DATA = {
    "ahv_cost": {
        "name": "Total AHV cost",
        "unit": "USD",
    },
    "total_logistic_cost": {
        "name": "Total logistic cost",
        "unit": "USD",
    },
    "total_move_cost": {
        "name": "Total move cost",
        "unit": "USD",
    },
    "total_fuel_cost": {
        "name": "Total fuel cost",
        "unit": "USD",
    },
    "total_transit_co2": {
        "name": "Total transit CO2 emission",
        "unit": "tons",
    },
    "total_support_co2": {
        "name": "Total support CO2 emission",
        "unit": "tons",
    },
    "total_rig_and_spread_cost": {
        "name": "Total rig and spread cost",
        "unit": "USD",
    },
}


def update_study_metrics(apps, _):
    StudyMetricModel = apps.get_model('studies', 'StudyMetric')
    StudyElementModel = apps.get_model('studies', 'StudyElement')

    StudyElementModel.objects.filter(metric__key="cost_per_day").delete()
    StudyElementModel.objects.filter(metric__key="ahv_fuel").delete()
    StudyMetricModel.objects.filter(key="cost_per_day").delete()
    StudyMetricModel.objects.filter(key="ahv_fuel").delete()

    for key, data in METRICS_DATA.items():
        StudyMetricModel.objects.create(key=key, **data)


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_studyelementsemirigrelation_rig_plan_co2'),
    ]

    operations = [migrations.RunPython(update_study_metrics, migrations.RunPython.noop)]
