# Generated by Django 4.0.2 on 2022-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_auto_20220630_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymetric',
            name='is_drillship_compatible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studymetric',
            name='is_jackup_compatible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studymetric',
            name='is_semi_compatible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
