# Generated by Django 4.0.2 on 2022-07-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_auto_20220701_1412'),
        ('studies', '0015_auto_20220708_1052'),
    ]

    operations = []
