# Generated by Django 4.0.2 on 2022-09-15 08:55

from django.db import migrations


def add_cost_per_meter(apps, *args):
    StudyMetric = apps.get_model('studies', 'StudyMetric')

    StudyMetric.objects.create(
        name='Cost per meter',
        key='cost_per_meter',
        unit='USD',
        is_jackup_compatible=True,
        is_semi_compatible=True,
        is_drillship_compatible=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_merge_0013_auto_20220701_1412_0015_auto_20220708_1052'),
    ]

    operations = [migrations.RunPython(add_cost_per_meter)]
