# Generated by Django 4.0.2 on 2022-10-06 08:51

from django.db import migrations


def add_total_days(apps, *args):
    StudyMetric = apps.get_model('studies', 'StudyMetric')

    StudyMetric.objects.create(
        name='Total days',
        key='total_days',
        unit='',
        is_jackup_compatible=True,
        is_semi_compatible=True,
        is_drillship_compatible=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_auto_20220915_0855'),
    ]

    operations = [migrations.RunPython(add_total_days)]
