# Generated by Django 4.0.2 on 2022-05-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the tag in the KIMS system.', max_length=255)),
                ('data_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'vessel_id',
                    models.CharField(
                        help_text='Vessel ID in the kims system.', max_length=255, unique=True, verbose_name='Vessel ID'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=False, help_text='Data will be synced only for active vessels.'),
                ),
                ('synced_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('date', models.DateField()),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='values', to='kims.tag'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='kims.vessel'),
        ),
        migrations.AddConstraint(
            model_name='tagvalue',
            constraint=models.UniqueConstraint(fields=('tag', 'date'), name='unique_tag_value'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'vessel'), name='unique_vessel_tag_relation'),
        ),
    ]
