# Generated by Django 4.0.2 on 2022-07-04 10:23

import django.db.models.deletion
import pgcrypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KimsAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'username',
                    pgcrypto.fields.EncryptedCharField(
                        charset='utf-8', check_armor=True, cipher='aes', help_text='K-IMS API username', versioned=False
                    ),
                ),
                (
                    'password',
                    pgcrypto.fields.EncryptedCharField(
                        charset='utf-8', check_armor=True, cipher='aes', help_text='K-IMS API password', versioned=False
                    ),
                ),
                ('base_url', models.URLField(help_text='K-IMS API base URL')),
            ],
            options={'abstract': False, 'verbose_name': 'K-IMS API'},
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_id',
            field=models.CharField(
                help_text='Vessel ID in the K-IMS system.', max_length=255, verbose_name='Vessel ID'
            ),
        ),
        migrations.AddField(
            model_name='vessel',
            name='kims_api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kims.kimsapi'),
        ),
    ]
