# Generated by Django 4.0.2 on 2022-07-04 10:25

from django.db import migrations


def create_default_kims_api(apps, *args):
    KimsAPI = apps.get_model('kims', 'KimsAPI')
    Vessel = apps.get_model('kims', 'Vessel')

    default_api = KimsAPI.objects.create(username="change me", password="change me", base_url="change me")

    Vessel.objects.update(kims_api=default_api)


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0002_kimsapi_alter_vessel_vessel_id_vessel_kims_api'),
    ]

    operations = [migrations.RunPython(create_default_kims_api)]
