# Generated by Django 4.0.2 on 2022-07-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0003_auto_20220704_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='kims_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kims.kimsapi'),
        ),
    ]
