# Generated by Django 4.0.2 on 2022-07-05 11:06

from django.db import migrations


def delete_tag_values(apps, *args):
    TagValue = apps.get_model('kims', 'TagValue')

    TagValue.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0004_alter_vessel_kims_api'),
    ]

    operations = [migrations.RunPython(delete_tag_values)]
