# Generated by Django 4.0.2 on 2022-07-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0005_auto_20220705_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagvalue',
            old_name='value',
            new_name='mean',
        ),
        migrations.RenameField(
            model_name='vessel',
            old_name='synced_at',
            new_name='tags_synced_at',
        ),
        migrations.RenameField(
            model_name='vessel',
            old_name='vessel_id',
            new_name='kims_vessel_id',
        ),
        migrations.AlterField(
            model_name='tagvalue',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='kims_vessel_id',
            field=models.CharField(
                help_text='Vessel ID in the K-IMS system.', max_length=255, verbose_name='K-IMS Vessel ID'
            ),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='tags_synced_at',
            field=models.DateTimeField(help_text='Time of the last sync of tag values', null=True),
        ),
    ]
