# Generated by Django 4.0.2 on 2022-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0006_rename_value_tagvalue_mean_remove_vessel_synced_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tagvalue',
            constraint=models.CheckConstraint(
                check=models.Q(('date__minute', 0), ('date__second', 0)), name='even_tag_value_date_hour'
            ),
        ),
    ]
