# Generated by Django 4.0.2 on 2022-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0007_tagvalue_even_tag_value_date_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagvalue',
            name='average',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
