# Generated by Django 4.0.2 on 2022-11-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0008_tagvalue_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
