# Generated by Django 4.0.2 on 2022-11-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0009_tag_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
