# Generated by Django 4.0.2 on 2022-09-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kims', '0008_tagvalue_average'),
        ('tenants', '0008_auto_20220324_1446'),
        ('projects', '0032_auto_20220922_0905'),
        ('emps', '0015_merge_20220914_0613'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('draft', models.BooleanField(help_text='Draft assets will not be visible in the application.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kims.vessel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
