# Generated by Django 4.0.2 on 2022-09-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.AddField(
            model_name='asset',
            name='design_description',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='operator',
            field=models.CharField(default='Asset operator', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(default='Asset owner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(
                choices=[('JACKUP', 'Jackup'), ('SEMI', 'Semi-submersible'), ('DRILLSHIP', 'Drillship')],
                default='JACKUP',
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
