# Generated by Django 4.0.2 on 2022-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_remove_asset_description_asset_design_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='draft',
            field=models.BooleanField(),
        ),
    ]
