# Generated by Django 4.0.2 on 2022-09-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_alter_asset_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
