# Generated by Django 4.0.2 on 2022-09-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        ('emissions', '0004_asset_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.URLField(blank=True, help_text='Asset details material')),
                ('baseline', models.URLField(blank=True, help_text='Asset baseline material')),
                ('emp', models.URLField(blank=True, help_text='Asset EMP material')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
