# Generated by Django 4.0.2 on 2022-09-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_assetreferencematerial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CustomEmpInitiative',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('name', models.CharField(max_length=255)),
                        ('description', models.TextField()),
                        (
                            'group',
                            models.CharField(
                                choices=[
                                    ('POWER_SYSTEMS', 'Power systems'),
                                    ('BASELOADS', 'Baseloads'),
                                    ('PRODUCTIVITY', 'Productivity'),
                                ],
                                max_length=20,
                            ),
                        ),
                        ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset')),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='CustomEnergyUse',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('name', models.CharField(max_length=255)),
                        ('description', models.TextField()),
                        (
                            'asset',
                            models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset'),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='CustomEnergyUsePhase',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('value', models.FloatField()),
                        (
                            'season',
                            models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter')], max_length=16),
                        ),
                        (
                            'energy_use',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to='emissions.customenergyuse'
                            ),
                        ),
                        (
                            'mode',
                            models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannermode'),
                        ),
                        (
                            'phase',
                            models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannerphase'),
                        ),
                    ],
                    options={
                        'unique_together': {('energy_use', 'season', 'phase', 'mode')},
                    },
                ),
                migrations.CreateModel(
                    name='CustomEmpInitiativePhase',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('value', models.FloatField()),
                        (
                            'emp_initiative',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to='emissions.customempinitiative'
                            ),
                        ),
                        (
                            'mode',
                            models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannermode'),
                        ),
                        (
                            'phase',
                            models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wells.wellplannerphase'),
                        ),
                    ],
                    options={
                        'unique_together': {('emp_initiative', 'phase', 'mode')},
                    },
                ),
            ],
            database_operations=[],
        )
    ]
