# Generated by Django 4.0.2 on 2022-09-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0008_baseline_active_baseline_created_at_baseline_draft_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='baseline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('active', True)), fields=('asset', 'active'), name='unique_active_baseline'
            ),
        ),
    ]
