# Generated by Django 4.0.2 on 2022-09-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0010_baseline_active_never_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='asset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='emissions.asset'
            ),
        ),
    ]
