# Generated by Django 4.0.2 on 2022-09-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0011_alter_baseline_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
