# Generated by Django 4.0.2 on 2022-10-10 09:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('emissions', '0023_merge_20221012_1159'), ('projects', '0037_delete_customvessel')]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CustomVessel',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        (
                            'fuel_summer',
                            models.FloatField(
                                help_text='Summer daily fuel consumption in cubic meters',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        (
                            'fuel_winter',
                            models.FloatField(
                                help_text='Winter daily fuel consumption in cubic meters',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        (
                            'type',
                            models.CharField(
                                max_length=255,
                            ),
                        ),
                        ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.asset')),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ]
        )
    ]
