# Generated by Django 4.0.2 on 2022-10-04 09:10

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0012_baseline_deleted'),
        ('wells', '0042_auto_20221004_0909'),
        ('emps', '0019_auto_20220928_0707'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='WellPlannerPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                (
                    'color',
                    colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
                ),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='emissions.asset', related_name='phases'
                    ),
                ),
            ],
            options={
                'unique_together': {('asset', 'name')},
            },
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations, database_operations=[])]
