# Generated by Django 4.0.2 on 2022-09-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0041_alter_wellplanner_baseline'),
        ('emissions', '0012_baseline_deleted'),
    ]

    operations = [
        migrations.RenameModel(old_name='CustomEmpInitiative', new_name='EmissionReductionInitiative'),
        migrations.RenameModel(
            old_name='CustomEmpInitiativePhase',
            new_name='EmissionReductionInitiativeInput',
        ),
    ]
