# Generated by Django 4.0.2 on 2022-09-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0042_alter_wellplannercompletestep_emp_initiatives_and_more'),
        ('emissions', '0013_emissionmanagementplan_emissionreductioninitiative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionManagementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('draft', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='baseline',
            name='active_never_draft',
        ),
        migrations.RenameField(
            model_name='emissionreductioninitiative',
            old_name='group',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='emissionreductioninitiativeinput',
            old_name='emp_initiative',
            new_name='emission_reduction_initiative',
        ),
        migrations.AddField(
            model_name='emissionreductioninitiative',
            name='deployment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionreductioninitiative',
            name='vendor',
            field=models.CharField(default='Vendor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='emissionreductioninitiativeinput',
            unique_together={('emission_reduction_initiative', 'phase', 'mode')},
        ),
        migrations.AddConstraint(
            model_name='baseline',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('active', True), ('draft', False)), ('active', False), _connector='OR'),
                name='active_baseline_never_draft',
            ),
        ),
        migrations.AddField(
            model_name='emissionmanagementplan',
            name='baseline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.baseline'),
        ),
        migrations.AddField(
            model_name='emissionreductioninitiative',
            name='emission_management_plan',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionmanagementplan'
            ),
        ),
        migrations.AddConstraint(
            model_name='emissionmanagementplan',
            constraint=models.UniqueConstraint(
                condition=models.Q(('active', True)),
                fields=('baseline', 'active'),
                name='unique_active_emission_management_plan',
            ),
        ),
        migrations.AddConstraint(
            model_name='emissionmanagementplan',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('active', True), ('draft', False)), ('active', False), _connector='OR'),
                name='active_emission_management_plan_never_draft',
            ),
        ),
    ]
