# Generated by Django 4.0.2 on 2022-10-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0013_wellplannerphase'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='baselineinput',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.wellplannerphase'),
        ),
        migrations.AlterField(
            model_name='customempinitiativephase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.wellplannerphase'),
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations, database_operations=[])]
