# Generated by Django 4.0.2 on 2022-10-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0043_alter_wellplannercompletestep_phase_and_more'),
        ('emissions', '0014_wellplannerphase_alter_baselineinput_phase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WellPlannerPhase',
            new_name='CustomPhase',
        ),
    ]
