# Generated by Django 4.0.2 on 2022-10-10 12:15

from django.db import migrations


def migrate_tenant_for_vessel_type(apps, *args):
    CustomVessel = apps.get_model('emissions', 'CustomVessel')

    for custom_vessel in CustomVessel.objects.all():
        custom_vessel.tenant = custom_vessel.asset.tenant
        custom_vessel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0014_customvessel_tenant'),
    ]

    operations = [migrations.RunPython(migrate_tenant_for_vessel_type)]
