# Generated by Django 4.0.2 on 2022-09-30 11:11

from django.db import migrations


def create_emission_management_plan(apps, *args):
    EmissionManagementPlan = apps.get_model('emissions', 'EmissionManagementPlan')
    EmissionReductionInitiative = apps.get_model('emissions', 'EmissionReductionInitiative')
    Baseline = apps.get_model('emissions', 'Baseline')

    for emission_reduction_initiative in EmissionReductionInitiative.objects.all():
        emission_management_plan, _ = EmissionManagementPlan.objects.get_or_create(
            baseline=Baseline.objects.get(asset=emission_reduction_initiative.asset, active=True),
            defaults=dict(
                name='Emission Management Plan',
                description='Emission Management Plan description',
                version='1.0',
                draft=False,
                active=True,
            ),
        )
        emission_reduction_initiative.emission_management_plan = emission_management_plan
        emission_reduction_initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0014_emissionmanagementplan_and_more'),
    ]

    operations = [migrations.RunPython(create_emission_management_plan)]
