# Generated by Django 4.0.2 on 2022-10-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        ('emissions', '0015_rename_wellplannerphase_customphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='customphase',
            name='phase',
            field=models.ForeignKey(
                null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.conceptphase'
            ),
        ),
        migrations.AlterField(
            model_name='customphase',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.asset'),
        ),
        migrations.AddField(
            model_name='customphase',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
