# Generated by Django 4.0.2 on 2022-10-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        ('wells', '0043_rename_vessel_completevesseluse_vessel_type_and_more'),
        ('emissions', '0015_auto_20221010_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomVessel',
            new_name='VesselType',
        ),
    ]
