# Generated by Django 4.0.2 on 2022-09-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0015_auto_20220930_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionreductioninitiative',
            name='asset',
        ),
        migrations.AlterField(
            model_name='emissionreductioninitiative',
            name='emission_management_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionmanagementplan'),
        ),
    ]
