# Generated by Django 4.0.2 on 2022-10-05 05:56

from django.db import migrations

PHASE_NAMES = (
    'Transit / Stand by',
    'Positioning',
    'Top hole section',
    'Transport section',
    'Reservoir section',
    'Completion',
    'Well intervention',
    'Plug and abandon',
    'Waiting on weather',
    'Downtime',
    'Mobilizing',
    'Warm stacked',
    'Cold stacked',
)


def create_concept_phases(apps, _):
    TenantModel = apps.get_model('tenants', 'Tenant')
    ConceptPhaseModel = apps.get_model('emissions', 'ConceptPhase')
    CustomPhaseModel = apps.get_model('emissions', 'CustomPhase')

    for tenant in TenantModel.objects.all():
        for name in PHASE_NAMES:
            concept_well_planner_phase, _ = ConceptPhaseModel.objects.get_or_create(
                tenant=tenant,
                name=name,
                description=f"{name} phase",
            )
            CustomPhaseModel.objects.filter(
                asset__tenant=tenant,
                name=name,
            ).update(phase=concept_well_planner_phase, description=f"{name} phase")


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0016_conceptphase_customphase_phase'),
    ]

    operations = [
        migrations.RunPython(create_concept_phases, migrations.RunPython.noop),
    ]
