# Generated by Django 4.0.2 on 2022-10-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        ('emissions', '0016_rename_customvessel_vesseltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesseltype',
            name='asset',
        ),
        migrations.AlterField(
            model_name='vesseltype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
    ]
