# Generated by Django 4.0.2 on 2022-10-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0016_remove_emissionreductioninitiative_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionmanagementplan',
            name='baseline',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='emission_management_plans',
                to='emissions.baseline',
            ),
        ),
        migrations.AlterField(
            model_name='emissionreductioninitiative',
            name='emission_management_plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='emission_reduction_initiative',
                to='emissions.emissionmanagementplan',
            ),
        ),
    ]
