# Generated by Django 4.0.2 on 2022-10-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0017_auto_20221005_0556'),
        ('wells', '0044_auto_20221005_0924'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='WellPlannerMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                (
                    'asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='emissions.asset'
                    ),
                ),
            ],
            options={
                'unique_together': {('asset', 'name')},
            },
        ),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=state_operations)]
