# Generated by Django 4.0.2 on 2022-10-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0018_vesseltype_co2_per_fuel_vesseltype_co2_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vesseltype',
            old_name='fuel_summer',
            new_name='fuel_consumption_summer',
        ),
        migrations.RenameField(
            model_name='vesseltype',
            old_name='fuel_winter',
            new_name='fuel_consumption_winter',
        ),
    ]
