# Generated by Django 4.0.2 on 2022-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0019_rename_fuel_summer_vesseltype_fuel_consumption_summer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesseltype',
            name='deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
