# Generated by Django 4.0.2 on 2022-10-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('emissions', '0021_helicoptertype'), ('projects', '0047_delete_helicoptertype')]

    operations = [
        migrations.RenameField(
            model_name='helicoptertype',
            old_name='fuel',
            new_name='fuel_consumption',
        ),
        migrations.RenameField(
            model_name='helicoptertype',
            old_name='name',
            new_name='type',
        ),
    ]
