# Generated by Django 4.0.2 on 2022-10-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0017_alter_emissionmanagementplan_baseline_and_more'),
        ('emissions', '0022_auto_20221005_2052'),
    ]

    operations = []
