# Generated by Django 4.0.2 on 2022-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0022_auto_20221005_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineinput',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
