# Generated by Django 4.0.2 on 2022-10-11 10:42

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0024_auto_20221011_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baselineinput',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='baselineinput',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='baselineinput',
            constraint=models.UniqueConstraint(
                fields=('baseline', 'phase', 'mode', 'season'), name='unique_baseline_input'
            ),
        ),
        migrations.AddConstraint(
            model_name='baselineinput',
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable['DEFERRED'],
                fields=('baseline', 'order'),
                name='unique_baseline_input_order',
            ),
        ),
    ]
