# Generated by Django 4.0.2 on 2022-10-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0019_rename_fuel_summer_vesseltype_fuel_consumption_summer_and_more'),
        ('emissions', '0025_alter_baselineinput_unique_together_and_more'),
    ]

    operations = []
