# Generated by Django 4.0.2 on 2022-10-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0026_merge_20221013_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionreductioninitiativeinput',
            name='emission_reduction_initiative',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='emission_reduction_initiative_inputs',
                to='emissions.emissionreductioninitiative',
            ),
        ),
    ]
