# Generated by Django 4.0.2 on 2022-10-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0020_vesseltype_deleted'),
        ('emissions', '0026_merge_20221013_1230'),
    ]

    operations = []
