# Generated by Django 4.0.2 on 2022-10-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0027_alter_emissionreductioninitiativeinput_emission_reduction_initiative'),
        ('emissions', '0027_merge_20221018_0853'),
    ]

    operations = []
