# Generated by Django 4.0.2 on 2022-10-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0023_remove_helicoptertype_nox_and_more'),
        ('emissions', '0027_merge_20221018_0853'),
    ]

    operations = []
