# Generated by Django 4.0.2 on 2022-10-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0028_merge_20221018_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionreductioninitiative',
            name='emission_management_plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='emission_reduction_initiatives',
                to='emissions.emissionmanagementplan',
            ),
        ),
    ]
