# Generated by Django 4.0.2 on 2022-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0029_assetreferencematerial_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emissionmanagementplan',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('active', True), ('deleted', False)), ('active', False), _connector='OR'),
                name='active_emission_management_plan_never_deleted',
            ),
        ),
    ]
