# Generated by Django 4.0.2 on 2022-10-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0028_merge_20221019_1209'),
        ('emissions', '0029_alter_emissionreductioninitiative_emission_management_plan'),
    ]

    operations = []
