# Generated by Django 4.0.2 on 2022-10-26 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_auto_20220324_1446'),
        ('emissions', '0030_merge_20221020_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('STEEL', 'Steel'),
                            ('CEMENT', 'Cement'),
                            ('BULK', 'Bulk'),
                            ('CHEMICALS', 'Chemicals'),
                        ],
                        max_length=64,
                    ),
                ),
                ('type', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                (
                    'co2',
                    models.FloatField(
                        help_text='Ton CO2/unit', validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
