# Generated by Django 4.0.2 on 2022-10-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_merge_20221020_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='green_house_gas_class_notation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
