# Generated by Django 4.0.2 on 2022-10-24 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_merge_20221020_1324'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ExternalEnergySupply',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('type', models.CharField(help_text='External energy supply type', max_length=255)),
                        (
                            'capacity',
                            models.FloatField(
                                help_text='Capacity (MWh/day)', validators=[django.core.validators.MinValueValidator(0)]
                            ),
                        ),
                        (
                            'co2',
                            models.FloatField(
                                help_text='Ton CO2/MWh', validators=[django.core.validators.MinValueValidator(0)]
                            ),
                        ),
                        (
                            'nox',
                            models.FloatField(
                                help_text='Kg NOx / MWh', validators=[django.core.validators.MinValueValidator(0)]
                            ),
                        ),
                        (
                            'generator_efficiency_factor',
                            models.FloatField(
                                help_text='Generator efficiency factor (MWh/m3 fuel)',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        (
                            'asset',
                            models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='emissions.asset'),
                        ),
                    ],
                    options={
                        'verbose_name': 'External Energy Supply',
                        'verbose_name_plural': 'External Energy Supplies',
                    },
                ),
            ]
        )
    ]
