# Generated by Django 4.0.2 on 2022-10-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0030_emissionmanagementplan_active_emission_management_plan_never_deleted'),
        ('emissions', '0030_emissionreductioninitiative_deleted'),
        ('emissions', '0030_merge_20221020_1324'),
    ]

    operations = []
