# Generated by Django 4.0.2 on 2022-10-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0031_asset_green_house_gas_class_notation'),
        ('emissions', '0031_merge_20221027_0732'),
    ]

    operations = []
