# Generated by Django 4.0.2 on 2022-10-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0031_asset_green_house_gas_class_notation'),
        ('emissions', '0031_externalenergysupply'),
    ]

    operations = []
