# Generated by Django 4.0.2 on 2022-10-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0032_merge_20221027_1008'),
        ('emissions', '0033_auto_20221024_1142'),
    ]

    operations = []
