# Generated by Django 4.0.2 on 2022-10-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0031_helicoptertype_deleted'),
        ('emissions', '0034_merge_20221027_1055'),
    ]

    operations = []
