# Generated by Django 4.0.2 on 2022-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0035_merge_20221028_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helicoptertype',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
