# Generated by Django 4.0.2 on 2022-11-04 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0036_alter_helicoptertype_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionreductioninitiative',
            name='deployment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
