# Generated by Django 4.0.2 on 2022-11-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0031_materialtype'),
        ('emissions', '0036_alter_helicoptertype_deleted'),
    ]

    operations = []
