# Generated by Django 4.0.2 on 2022-11-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0036_alter_helicoptertype_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
    ]
