# Generated by Django 4.0.2 on 2022-11-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0037_alter_emissionreductioninitiative_deployment_date'),
        ('emissions', '0037_remove_asset_operator_remove_asset_owner'),
    ]

    operations = []
