# Generated by Django 4.0.2 on 2022-11-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0037_merge_20221107_0941'),
        ('emissions', '0038_merge_20221108_0740'),
    ]

    operations = []
