# Generated by Django 4.0.2 on 2022-11-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0038_materialtype_deleted'),
        ('emissions', '0039_merge_20221108_0839'),
    ]

    operations = []
