# Generated by Django 4.0.2 on 2022-11-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0039_merge_20221108_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='category',
            field=models.CharField(
                choices=[('STEEL', 'Steel'), ('CEMENT', 'Cement'), ('BULK', 'Bulk'), ('CHEMICALS', 'Chemicals')],
                max_length=9,
            ),
        ),
    ]
