# Generated by Django 4.0.2 on 2022-11-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0040_alter_materialtype_category'),
        ('emissions', '0040_merge_20221108_0848'),
    ]

    operations = []
