# Generated by Django 4.0.2 on 2022-11-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0041_merge_20221108_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(
                choices=[
                    ('JACKUP', 'Jackup'),
                    ('SEMI', 'Semi-submersible'),
                    ('DRILLSHIP', 'Drillship'),
                    ('FIXED_PLATFORM', 'Fixed platform'),
                ],
                max_length=16,
            ),
        )
    ]
