# Generated by Django 4.0.2 on 2022-11-09 11:05

import random

from django.db import migrations


def get_random_name(old_name, Asset):
    while True:
        number = random.randint(1, 99999)
        new_name = f'{old_name[:250]}{number}'
        if not Asset.objects.filter(name=new_name, deleted=False).exists():
            return new_name


def migrate_asset_name(apps, *args):
    Asset = apps.get_model('emissions', 'Asset')
    for asset in Asset.objects.filter(deleted=False).order_by('id'):
        if Asset.objects.filter(deleted=False, name=asset.name).exclude(pk=asset.pk).exists():
            asset.name = get_random_name(asset.name, Asset)
            asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0042_alter_asset_type_alter_materialtype_category'),
    ]

    operations = [migrations.RunPython(migrate_asset_name)]
