# Generated by Django 4.0.2 on 2022-11-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0009_tag_deleted'),
        ('emissions', '0043_auto_20221109_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='vessel',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kims.vessel'
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted', False)), fields=('name',), name='unique_asset_name'
            ),
        ),
    ]
