# Generated by Django 4.0.2 on 2022-11-09 14:06

from django.db import migrations


def unlink_vessels(apps, *args):
    Asset = apps.get_model('emissions', 'Asset')
    Asset.objects.all().update(vessel=None)


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0044_alter_asset_vessel_asset_unique_asset_name'),
    ]

    operations = [migrations.RunPython(unlink_vessels)]
