# Generated by Django 4.0.2 on 2022-11-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kims', '0009_tag_deleted'),
        ('emissions', '0045_auto_20221109_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='vessel',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kims.vessel'
            ),
        ),
    ]
