# Generated by Django 4.0.2 on 2022-11-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0042_alter_materialtype_category'),
        ('emissions', '0046_alter_asset_vessel'),
    ]

    operations = []
