# Generated by Django 4.0.2 on 2022-11-10 14:17
import random

from django.db import migrations


def get_random_name(*, old_name, asset, EmissionManagementPlan):
    while True:
        number = random.randint(1, 99999)
        new_name = f'{old_name[:250]}{number}'
        if not EmissionManagementPlan.objects.filter(name=new_name, deleted=False, baseline__asset=asset).exists():
            return new_name


def migrate_emission_management_plan_name(apps, *args):
    EmissionManagementPlan = apps.get_model('emissions', 'EmissionManagementPlan')
    for emission_management_plan in (
        EmissionManagementPlan.objects.filter(deleted=False).select_related('baseline__asset').order_by('id')
    ):
        if (
            EmissionManagementPlan.objects.filter(
                deleted=False,
                name=emission_management_plan.name,
                baseline__asset=emission_management_plan.baseline.asset,
            )
            .exclude(pk=emission_management_plan.pk)
            .exists()
        ):
            emission_management_plan.name = get_random_name(
                old_name=emission_management_plan.name,
                asset=emission_management_plan.baseline.asset,
                EmissionManagementPlan=EmissionManagementPlan,
            )
            emission_management_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0047_merge_20221110_1232'),
    ]

    operations = [migrations.RunPython(migrate_emission_management_plan_name)]
