# Generated by Django 4.0.2 on 2022-11-15 13:50

import random

from django.db import migrations


def get_unique_name(name, queryset):
    new_name = name

    while queryset.filter(name=new_name).exists():
        new_name = f'{name[:250]}{random.randint(1, 99999)}'

    return new_name


def migrate_emission_reduction_initiative_name(apps, *args):
    EmissionReductionInitiativeModel = apps.get_model('emissions', 'EmissionReductionInitiative')

    for emission_reduction_initiative in EmissionReductionInitiativeModel.objects.filter(deleted=False).order_by('id'):
        emission_reduction_initiative.name = get_unique_name(
            emission_reduction_initiative.name,
            EmissionReductionInitiativeModel.objects.filter(deleted=False).exclude(pk=emission_reduction_initiative.pk),
        )
        emission_reduction_initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0047_merge_20221110_1232'),
    ]

    operations = [
        migrations.RunPython(migrate_emission_reduction_initiative_name, migrations.RunPython.noop),
    ]
