# Generated by Django 4.0.2 on 2022-11-10 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0048_auto_20221110_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionmanagementplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionmanagementplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
