# Generated by Django 4.0.2 on 2022-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0050_auto_20221114_0907'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='baseline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted', False)), fields=('asset', 'name'), name='unique_baseline_name'
            ),
        ),
    ]
