# Generated by Django 4.0.2 on 2022-11-14 09:47

from django.db import migrations
from django.utils import timezone


def migrate_phases(apps, *args):
    ConceptPhase = apps.get_model('emissions', 'ConceptPhase')
    CustomPhase = apps.get_model('emissions', 'CustomPhase')

    # updated phases
    transit_phases = ConceptPhase.objects.filter(name='Transit / Stand by')
    CustomPhase.objects.filter(name='Transit').update(name=f'Transit {timezone.now().isoformat()}'[:32])
    CustomPhase.objects.filter(phase__in=transit_phases).update(name='Transit', description='Transit phase')
    transit_phases.update(name='Transit', description='Transit phase')

    # removed phases
    transport_section_phases = ConceptPhase.objects.filter(name='Transport section')
    mobilizing_phases = ConceptPhase.objects.filter(name='Mobilizing')
    warm_stacked_phases = ConceptPhase.objects.filter(name='Warm stacked')
    cold_stacked_phases = ConceptPhase.objects.filter(name='Cold stacked')

    for phases in [transport_section_phases, mobilizing_phases, warm_stacked_phases, cold_stacked_phases]:
        CustomPhase.objects.filter(phase__in=phases).update(phase=None)
        phases.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0051_baseline_unique_baseline_name'),
    ]

    operations = [migrations.RunPython(migrate_phases)]
