# Generated by Django 4.0.2 on 2022-11-14 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0052_auto_20221114_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptmode',
            name='asset_types',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('JACKUP', 'Jackup'),
                        ('SEMI', 'Semi-submersible'),
                        ('DRILLSHIP', 'Drillship'),
                        ('FIXED_PLATFORM', 'Fixed platform'),
                    ],
                    max_length=16,
                ),
                default=[],
                help_text='Compatible asset types',
                size=None,
            ),
            preserve_default=False,
        ),
    ]
