# Generated by Django 4.0.2 on 2022-11-14 10:41

from django.db import migrations
from django.utils import timezone


class AssetType:
    JACKUP = 'JACKUP'
    SEMI = 'SEMI'
    DRILLSHIP = 'DRILLSHIP'
    FIXED_PLATFORM = 'FIXED_PLATFORM'


def migrate_modes(apps, *args):
    ConceptMode = apps.get_model('emissions', 'ConceptMode')
    CustomMode = apps.get_model('emissions', 'CustomMode')

    for old_mode_name, new_mode_name, asset_types in [
        (
            'Transit / Stand by',
            'Transit',
            (AssetType.JACKUP, AssetType.FIXED_PLATFORM, AssetType.SEMI, AssetType.DRILLSHIP),
        ),
        ('Pos moore', 'Poos Moor ATA', (AssetType.SEMI,)),
        ('Dynamic positioning', 'DP', (AssetType.SEMI, AssetType.DRILLSHIP)),
        ('Anchor', 'Fixed', (AssetType.JACKUP, AssetType.FIXED_PLATFORM)),
    ]:
        concept_modes = ConceptMode.objects.filter(name=old_mode_name)
        CustomMode.objects.filter(name=new_mode_name).update(name=f'{new_mode_name} {timezone.now().isoformat()}'[:32])
        CustomMode.objects.filter(mode__in=concept_modes).update(
            name=new_mode_name,
            description=f'{new_mode_name} mode',
        )
        concept_modes.update(name=new_mode_name, description=f'{new_mode_name} mode', asset_types=asset_types)


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0053_conceptmode_asset_types'),
    ]

    operations = [migrations.RunPython(migrate_modes)]
