# Generated by Django 4.0.2 on 2022-11-14 12:15

from django.db import migrations


def unlink_concept_modes(apps, *args):
    CustomMode = apps.get_model('emissions', 'CustomMode')

    for custom_mode in CustomMode.objects.filter(mode__isnull=False).select_related('mode'):
        if custom_mode.asset.type not in custom_mode.mode.asset_types:
            custom_mode.mode = None
            custom_mode.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0054_auto_20221114_1041'),
    ]

    operations = [migrations.RunPython(unlink_concept_modes)]
