# Generated by Django 4.0.2 on 2022-11-14 12:19

from django.db import migrations


class AssetSeason:
    SUMMER = 'SUMMER'
    WINTER = 'WINTER'


def add_concept_modes_and_phases_to_inputs(apps, *args):
    Asset = apps.get_model('emissions', 'Asset')
    Baseline = apps.get_model('emissions', 'Baseline')
    EmissionReductionInitiative = apps.get_model('emissions', 'EmissionReductionInitiative')
    BaselineInput = apps.get_model('emissions', 'BaselineInput')
    EmissionReductionInitiativeInput = apps.get_model('emissions', 'EmissionReductionInitiativeInput')
    CustomPhase = apps.get_model('emissions', 'CustomPhase')
    CustomMode = apps.get_model('emissions', 'CustomMode')

    for asset in Asset.objects.all():
        phases = CustomPhase.objects.filter(asset=asset)
        modes = CustomMode.objects.filter(asset=asset)
        for baseline in Baseline.objects.filter(asset=asset):
            for phase in phases:
                for mode in modes:
                    for season in [AssetSeason.SUMMER, AssetSeason.WINTER]:
                        last_input = BaselineInput.objects.filter(baseline=baseline).order_by('order').last()
                        BaselineInput.objects.get_or_create(
                            baseline=baseline,
                            phase=phase,
                            mode=mode,
                            season=season,
                            defaults=dict(value=0, order=last_input.order + 1 if last_input else 0),
                        )
            for emission_reduction_initiative in EmissionReductionInitiative.objects.filter(
                emission_management_plan__baseline=baseline
            ):
                for phase in phases:
                    for mode in modes:
                        EmissionReductionInitiativeInput.objects.get_or_create(
                            emission_reduction_initiative=emission_reduction_initiative,
                            phase=phase,
                            mode=mode,
                            defaults=dict(value=0),
                        )


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0055_auto_20221114_1215'),
    ]

    operations = [migrations.RunPython(add_concept_modes_and_phases_to_inputs)]
