# Generated by Django 4.0.2 on 2022-11-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0044_auto_20221110_0919'),
        ('emissions', '0056_auto_20221114_1219'),
    ]

    operations = []
