# Generated by Django 4.0.2 on 2022-11-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0048_auto_20221115_1350'),
        ('emissions', '0056_auto_20221114_1219'),
    ]

    operations = []
