# Generated by Django 4.0.2 on 2022-11-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0057_merge_0044_auto_20221110_0919_0056_auto_20221114_1219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conceptphase',
            unique_together=set(),
        ),
    ]
