# Generated by Django 4.0.2 on 2022-11-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0057_merge_0048_auto_20221115_1350_0056_auto_20221114_1219'),
        ('emissions', '0058_alter_conceptphase_unique_together'),
    ]

    operations = []
