# Generated by Django 4.0.2 on 2022-11-20 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0059_merge_20221118_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselineinput',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='emissionreductioninitiativeinput',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
