# Generated by Django 4.0.2 on 2022-11-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_user_options_user_company_user_role_and_more'),
        ('emissions', '0061_auto_20221121_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wellname',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_well_name'),
        ),
    ]
