# Generated by Django 4.0.2 on 2022-11-29 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0056_wellplanner_deleted'),
        ('emissions', '0061_auto_20221121_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellPlannedStepMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quota', models.BooleanField()),
                (
                    'material_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.materialtype'),
                ),
                (
                    'step',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='materials',
                        to='wells.wellplannerplannedstep',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellCompleteStepMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quota', models.BooleanField()),
                (
                    'material_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.materialtype'),
                ),
                (
                    'step',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='materials',
                        to='wells.wellplannercompletestep',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='externalenergysupply',
            name='asset',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name='external_energy_supply', to='emissions.asset'
            ),
        ),
    ]
