# Generated by Django 4.0.2 on 2022-11-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0062_wellname_wellname_unique_well_name'),
        ('emissions', '0062_wellplannedstepmaterial_wellcompletestepmaterial'),
    ]

    operations = []
