# Generated by Django 4.0.2 on 2022-12-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0063_merge_20221130_1241'),
        ('emissions', '0063_plannedvesseluse_completevesseluse'),
    ]

    operations = []
