# Generated by Django 4.0.2 on 2022-12-05 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0069_remove_plannedhelicopteruse_helicopter_type_and_more'),
        ('emissions', '0063_plannedvesseluse_completevesseluse'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PlannedHelicopterUse',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        (
                            'trips',
                            models.IntegerField(
                                help_text='Number of round trips',
                                validators=[django.core.validators.MinValueValidator(1)],
                            ),
                        ),
                        (
                            'trip_duration',
                            models.IntegerField(
                                help_text='Flight time per round trip (minutes)',
                                validators=[apps.core.validators.GreaterThanValidator(0)],
                            ),
                        ),
                        (
                            'exposure_against_current_well',
                            models.FloatField(
                                help_text='Percentage exposure against current well',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        (
                            'quota_obligation',
                            models.FloatField(
                                help_text='Percentage quota obligation',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        (
                            'helicopter_type',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT, to='emissions.helicoptertype'
                            ),
                        ),
                        (
                            'well_planner',
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplanner'),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='CompleteHelicopterUse',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        (
                            'trips',
                            models.IntegerField(
                                help_text='Number of round trips',
                                validators=[django.core.validators.MinValueValidator(1)],
                            ),
                        ),
                        (
                            'trip_duration',
                            models.IntegerField(
                                help_text='Flight time per round trip (minutes)',
                                validators=[apps.core.validators.GreaterThanValidator(0)],
                            ),
                        ),
                        (
                            'exposure_against_current_well',
                            models.FloatField(
                                help_text='Percentage exposure against current well',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        (
                            'quota_obligation',
                            models.FloatField(
                                help_text='Percentage quota obligation',
                                validators=[django.core.validators.MinValueValidator(0)],
                            ),
                        ),
                        ('approved', models.BooleanField()),
                        (
                            'helicopter_type',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT, to='emissions.helicoptertype'
                            ),
                        ),
                        (
                            'well_planner',
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wellplanner'),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ]
        )
    ]
