# Generated by Django 4.0.2 on 2022-12-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0064_merge_20221206_1456'),
        ('emissions', '0064_plannedhelicopteruse_completehelicopteruse'),
    ]

    operations = []
