# Generated by Django 4.0.2 on 2022-12-20 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0067_alter_baselineco2_options_alter_targetco2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineco2',
            name='boilers',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetco2',
            name='boilers',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
