# Generated by Django 4.0.2 on 2022-12-16 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0067_alter_baselineco2_options_alter_targetco2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='boilers_fuel_consumption_summer',
            field=models.FloatField(
                default=0,
                help_text='Boilers fuel consumption summer (m3 fuel/day)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseline',
            name='boilers_fuel_consumption_winter',
            field=models.FloatField(
                default=0,
                help_text='Boilers fuel consumption winter (m3 fuel/day)',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
