# Generated by Django 4.0.2 on 2022-12-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0068_baseline_boilers_fuel_consumption_summer_and_more'),
        ('emissions', '0068_baselineco2_boilers_targetco2_boilers'),
    ]

    operations = []
