version: "3"
   
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/code
    ports:
      - '5432:5432'

  redis:
    hostname: redis
    image: redis:6.2.1
    volumes:
      - redis-data:/data

  api: &api
    build: .
    command: bash entrypoint/api.sh
    env_file:
      - .env
    user: "${UID}:${GID}"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
      - redis

  celery-worker:
    <<: *api
    command: celery -A apps.app worker -l debug
    ports: []

  celery-beat:
    <<: *api
    command: celery -A apps.app beat -l debug
    ports: []

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  flower:
      image: mher/flower
      ports:
        - 5555:5555
      environment:
        CELERY_BROKER_URL: $CELERY_BROKER_URL
        CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
        FLOWER_BASIC_AUTH: $FLOWER_USERNAME:$FLOWER_PASSWORD
      depends_on:
        - celery-worker
        - celery-beat
        - redis

volumes:
  pgdata:
  redis-data:
  elasticsearch-data:
